### ISSUE TITLE
Limit using Points and duration on demand

### ISSUE THREAD

**Issue by Miguel-Herrero** [animir/node-rate-limiter-flexible#10]
Hi @animir Congratulations for your library! Very complete!

I was using [Express Rate Limit](https://www.npmjs.com/package/express-rate-limit) as the rate limiter for my Express API. However, I have recently changed my app to use Nodejs' [Cluster](https://nodejs.org/api/cluster.html) module, so I had to look for another library that supported cluster features. And I found Rate Limiter Flexible.

However I don't know how to implement the same functionality I had: **some endpoints had a different limitation configuration, but limitation/blocking was global**. For example: `/login` has a limit of 10 requests per minute, and `/users/:userId` has a limit of 1000 requests per 5 minutes. If a user consumed the 10 requests in `/login`, he could not request `/user/:userId` because he had already reached a 429 error status from another endpoint (`/login`).

It was a simple middleware like:
```
// Router middleware
router.post('/login', RateLimiter.limiter(10, 1 * 60), myController) // 10 req in 1 min
router.get('/users/:userId', RateLimiter.limiter(1000, 5 * 60), myController) // 1000 req in 5 min

// Rate limiter
import rateLimit from 'express-rate-limit'
export function limiter (requests, intervalSeconds) {
  return rateLimit({
    windowMs: intervalSeconds || config.defaultIntervalSeconds,
    max: requests || config.defaultMaxRequests,
    onLimitReached, // Log the error
    keyGenerator, // Generate a key from the IP
    skip: () => !config.isEnabled
  })
}
```

However, I don't know how to implement it with Rate Limiter Flexible, as if I create two instances (one for each endpoint), if user consumes all points in one endpoint, **he can still consume points of the second endpoint**:

```
export function limiter (requests, intervalSeconds) {
  return function (req, res, next) {
    // Skip rate-limiter if not enabled
    if (config.isEnabled !== true) return next()

    const allowedRequests = requests || config.maxRequests
    const duration = intervalSeconds || config.intervalSeconds

    rateLimiter = new RateLimiterCluster({
      keyPrefix: 'rate-limiter',
      points: allowedRequests,
      duration,
      timeoutMs: 3000
    })

    return rateLimiter.consume(keyGenerator(req))
      .then(()=> {
        return next()
      })
      .catch(()=> {
        return res.status(429).json({})
      })
  }
}
```

Is there a way to achieve the same functionality in Rate Limiter Flexible? Or do you think of a way to handle this with this library?

Thank you so much.

**Comment by animir** [comment]
@Miguel-Herrero Thank you for details.
First of all, I think, it is strange behaviour of `express-rate-limit`. Why should app block all other endpoints if user types password wrong 10 times per minute? What if application has password reset endpoint and it is limited too, so it is blocked too because of other endpoint limits. It doesn't right.

Anyway, if you want to make that global, you should create a limiter which has 200 points per minute. (it fits your requirement of 1000 points per 5 minutes). consume 20 points every try to login and consume 1 point every request to user endpoint.

You may also have global limiter and limiters for every endpoint. Consume from global every request to backend and consume from other depending on route path, then decide on both results. 

I'm going to think, if `RateLimiterUnion` may be improved for your use case. It consumes the same number of points from all united limiters at once, which doesn't help you in this case.

Let me know, if that makes sense.

**Comment by animir** [comment]
One more option:
Every limiter has [`block` ](https://github.com/animir/node-rate-limiter-flexible#ratelimiterres-object) method. If auth limiter reaches limit, it returns [`RateLimiterRes object` ](https://github.com/animir/node-rate-limiter-flexible#ratelimiterres-object) with `msBeforeNext` value, which is milliseconds before client can make requests again.  Then get user limiter (and all other limiters) blocks this IP for `Math.floor(res.msBeforeNext / 1000)` seconds.

Hope this helps.

**Comment by Miguel-Herrero** [comment]
Hi @animir 
Eventually I did as you say: make a global limiter with the least restrictive configuration, and add a limiter for each endpoint (with more restrictive configurations). Each time a user requests an endpoint, consumes both from the Global limiter and the Endpoint limiter.

This way I can control that the user cannot hit an endpoint beyond its restrictive limiter, and in general the user cannot hit the app beyond the Global limiter.

The original idea was to block the whole app for that user in case of brute-force attack, but it's better to block only endpoints. It allows to more granular control over each user/endpoint.

> I'm going to think, if RateLimiterUnion may be improved for your use case. It consumes the same number of points from all united limiters at once, which doesn't help you in this case.

I don't think you should spent time if I was the only one with that question, and eventually I changed my mind towards your proposal.

Thank you for your kind help. And congrats for this marvelous library. Now, I shall close the issue.
