### ISSUE TITLE
Fix README "Retry-After" example

### ISSUE THREAD

**Issue by sebestindragos** [animir/node-rate-limiter-flexible#104]
This is a small fix, the `RateLimiterRes object` section of the README has this example of how to set the `Retry-After` header:

```javascript
const headers = {
  "Retry-After": rateLimiterRes.msBeforeNext / 1000,
  "X-RateLimit-Limit": opts.points,
  "X-RateLimit-Remaining": rateLimiterRes.remainingPoints,
  "X-RateLimit-Reset": new Date(Date.now() + rateLimiterRes.msBeforeNext)
}
```

I believe [the spec](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After) for that HTTP header mentions the unit values are in seconds, so the example shoul say `* 1000` instead of `/ 1000`.
```
"Retry-After": rateLimiterRes.msBeforeNext * 1000,
```

**Comment by animir** [comment]
@sebestindragos I think, you get microseconds if multiply milliseconds to 1000

**Comment by sebestindragos** [comment]
🤦‍♂️nvm, it was late that night :))
