### ISSUE TITLE
Possible to change rate on runtime

### ISSUE THREAD

**Issue by figuibej** [animir/node-rate-limiter-flexible#105]
Its would be usefull if the can change the rate in runtime, im mean, im running a process and for some circustance i have to slow down the production / dequeing without restart the process

**Comment by animir** [comment]
@figuibej Hi, it is possible to do that now:
1. You can change any option in runtime, e.g. `rateLimiter.points = 50` will change number of allowed points.
2. You can change number of points consumed every request.
I hope, this helps.

**Comment by hectorgabucio** [comment]
@animir Can we change it also for rate limiters based on Redis? if I change points to 50 for example

**Comment by animir** [comment]
@hectorgabucio Yes, you can. Redis as any other storage doesn't make any decisions, but rate-limiter-flexible does. If you change any option, it affects how response from storage treated.
