### ISSUE TITLE
Change option name: from inmemoryBlockOnConsumed to inMemoryBlockOnConsumed

### ISSUE THREAD

**Issue by thernstig** [animir/node-rate-limiter-flexible#106]
Currently the API uses `inmemoryBlockOnConsumed` as an option, but it would be better if `inMemoryBlockOnConsumed`.

It is obviously more correct (camelCase), easier to read and it also does not give spelling error with spelling errors tools such https://github.com/streetsidesoftware/cspell

Any chance both `inmemoryBlockOnConsumed` and `inMemoryBlockOnConsumed` could be supported, where `inMemoryBlockOnConsumed` is mentioned in documentation and also takes precedence? I.e. the old name remains usable for backward compability.

**Comment by animir** [comment]
@thernstig Version `2.3.11` supports new `inMemoryBlockOnConsumed` and `inMemoryBlockDuration` options as well as just deprecated `inmemoryBlockOnConsumed` and `inmemoryBlockDuration`. Deprecated options will be supported until the next v3 major release.

**Comment by thernstig** [comment]
Hi @animir, how come release `2.3.11` did not show up at https://github.com/animir/node-rate-limiter-flexible/releases? I.e. there is no change log for users to be aware of this change.

**Comment by animir** [comment]
@thernstig It is there now. Thanks :)
