### ISSUE TITLE
Runtime options missing in TypeScript definition 

### ISSUE THREAD

**Issue by rijkvanzanten** [animir/node-rate-limiter-flexible#109]
As per https://github.com/animir/node-rate-limiter-flexible/issues/105, it's possible to change any of the rate limiter options in runtime by simply overriding the setting with a new value as follows: `rateLimiter.points = 15`.

However, this doesn't seem to be reflected in the TypeScript definitions. I'm faced with a `Property 'points' does not exist on type 'RateLimiterMemory'.` error. 

It seems like the following option getter/setters

https://github.com/animir/node-rate-limiter-flexible/blob/d070b20cadca8b17246653d851256ee5f859f35b/lib/RateLimiterAbstract.js#L22-L60

(and more) are missing from the index.d.ts file:

https://github.com/animir/node-rate-limiter-flexible/blob/d070b20cadca8b17246653d851256ee5f859f35b/lib/index.d.ts#L25-L43

**Comment by animir** [comment]
@rijkvanzanten Hi, thank you for reporting this issue. 
Feel free to create PR, if you have fixed it.

**Comment by rijkvanzanten** [comment]
@animir All set 👍🏻 Also added some more inline docs for improved usage within TS compatible IDEs
