### ISSUE TITLE
Add a additional example for Hapi.js using RateLimiterMemory 

### ISSUE THREAD

**Issue by DeniSpasovski** [animir/node-rate-limiter-flexible#115]
Hey Animir, 

Just wanted to share back my implementation of the RateLimiterMemory that I used with hapi.js 
Please let me know if you can add this to the wiki: 

    const Boom = require('@hapi/boom');
    const { RateLimiterMemory } = require('rate-limiter-flexible');
    
    const internals = {
      pluginName: 'rateLimitMemoryPlugin'
    };
    
    internals.rateLimiter = new RateLimiterMemory({
      points: 100, //number of requests
      duration: 60 //in seconds
    });
    
    module.exports = {
      name: internals.pluginName,
      version: '1.0.0',
      register: function (server) {
        server.ext('onPreAuth', async (request, h) => {
          try {
            await internals.rateLimiter.consume(request.info.remoteAddress);
            return h.continue;
          } catch (rej) {
            let error;
            if (rej instanceof Error) {
              // If some Redis error and 'insuranceLimiter' is not set
              error = Boom.internal('Try later');
            } else {
              // Not enough points to consume
              error = Boom.tooManyRequests('Rate limit exceeded');
              error.output.headers['Retry-After'] = Math.round(rej.msBeforeNext / 1000) || 1;
            }
    
            return error;
          }
        });
      }
    };

**Comment by animir** [comment]
@DeniSpasovski Hi, I see, you want to add Proxy support here. It brings additional context. If we provide this example, we should also make sure developers understand `x-forwarded-for` is not 100% reliable. How can we do that?

Also, this part `.split(':')[0]` may be not right. Could you explain it? As I understand, it get the first part of IP6 ?

**Comment by DeniSpasovski** [comment]
hey @animir that's really good point! maybe I should exclude the getRequestIdentifier as it is fairly coupled with my implementation - let me do that. 

And I had to use the port removal as Azure port forwarding works by assigning new port to every request it forwards - without it, the rate limiter will rarely kick in.

**Comment by animir** [comment]
@DeniSpasovski Where would you like to add this example?

**Comment by animir** [comment]
@DeniSpasovski There are so many docs on Wiki. While I appreciate your efforts and example, we should keep docs as short as possible

**Comment by DeniSpasovski** [comment]
closing.
