### ISSUE TITLE
undefined is not iterable on mongoDB backend

### ISSUE THREAD

**Issue by vdiez** [animir/node-rate-limiter-flexible#121]
I'm encountering this error from time to time:

```
undefined` is not iterable (cannot read property Symbol(Symbol.iterator)) TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at RateLimiterMongo._getRateLimiterRes (C:\www\projects\uefa_app\node_modules\rate-limiter-flexible\lib\RateLimiterMongo.js:117:15)
    at RateLimiterMongo._afterConsume (C:\www\projects\uefa_app\node_modules\rate-limiter-flexible\lib\RateLimiterStoreAbstract.js:51:22)
    at C:\www\projects\uefa_app\node_modules\rate-limiter-flexible\lib\RateLimiterStoreAbstract.js:205:16
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

https://github.com/animir/node-rate-limiter-flexible/blob/184d1d883583c53a5aff47726bc10afb6de3e4e9/lib/RateLimiterMongo.js#L116

Originally the issue seems to come from Mongo driver 4 as they have [removed the ops attribute](https://github.com/mongodb/node-mongodb-native/blob/4.0/HISTORY.md#-breaking-changes-1), needed when [using replaceOne](https://github.com/animir/node-rate-limiter-flexible/blob/184d1d883583c53a5aff47726bc10afb6de3e4e9/lib/RateLimiterMongo.js#L211)

**Comment by vdiez** [comment]
seems I have incorrectly linked to the Mongo changelog, it does not mention the disappearance of ops attribute. However is not listed any longer in the API:

http://mongodb.github.io/node-mongodb-native/4.0/interfaces/updateresult.html

**Comment by animir** [comment]
@vdiez Hi, thank you for reporting this.

What should be used instead of `ops` in MongoDB driver v4+ ?

**Comment by vdiez** [comment]
The thing is I don't know the reasoning behind line [206](https://github.com/animir/node-rate-limiter-flexible/blob/184d1d883583c53a5aff47726bc10afb6de3e4e9/lib/RateLimiterMongo.js#L206). My guess is we would avoid the duplicate key by not resetting the key again, as it's already part of the query part. But checking the blame on that line it mentions a fix on race conditions.

**Comment by vdiez** [comment]
Seems using findOneAndupdate fixes the problem
[patch.txt](https://github.com/animir/node-rate-limiter-flexible/files/6846904/patch.txt)

**Comment by vdiez** [comment]
Cleaning also the result.ops line, not needed any more.
[patch.txt](https://github.com/animir/node-rate-limiter-flexible/files/6846943/patch.txt)
