### ISSUE TITLE
How to rate limit an endpoint for each unique path params

### ISSUE THREAD

**Issue by hamitg** [animir/node-rate-limiter-flexible#123]
My endpoint is : **/orders/{orderId}/verify**. I want to apply a rate limiter for each unique order id so that **/orders/123/verify** should be different than **/orders/234/verify** in terms of rate limit count. One can visit the first one, let's say, only 10 times in a minute and for more requests, they should get a rate limit exceed error but they can also visit the second order id verify end point without a problem since they are requesting it with different orderIds. Is it possible to achieve that?

**Comment by animir** [comment]
@hamitg yes, it is possible, you can limit by order id
