### ISSUE TITLE
Project looks very interesting, but why use limiting at the app instead of reverse proxy like nginx?

### ISSUE THREAD

**Issue by samuelgoldenbaum** [animir/node-rate-limiter-flexible#13]
Project looks great, thanks for sharing. What advantages and disadvantages would there be to using limiting at app level and not before the app within a reverse proxy? My view is that the app is still being caught up processing the rate limiting of course and would prefer to keep this functionality in front of actual app servers. Or would this packages be used within a nodes.js reverse proxy before the application?

**Comment by animir** [comment]
@samuelgoldenbaum hi, thanks

nginx proxy with configured limit is better, if it is enough. any proxy, balancer is better to be honest
use this package only if you can not find other proxy/balancer solution.

yes, app is still caught up processing rate limiting, as you said. it is not big, you can get overall idea checking benchmark results on high traffic or test it in your environment. usually it is nothing, if request takes 3-15 ms more. rate-limiter-flexible can be used in applications with thousands of requests per second. Usually, such applications have much more issues than saving 3-15 ms per request.

**Comment by samuelgoldenbaum** [comment]
Thanks for the reply @animir, I am sure there is value in the project and appreciate your contribution to the OS community.
