### ISSUE TITLE
Callback on block released

### ISSUE THREAD

**Issue by shneor521** [animir/node-rate-limiter-flexible#131]
I want to run a callback when the block is released. 
Is there such a possibility at the moment?

**Comment by animir** [comment]
@shneor521 Hi, there is no this feature. It should be easy to implement for Memory limiter, not sure about store limiters.
Could you explain your needs in more details?

**Comment by shneor521** [comment]
When there is a blockage, I keep some value in the DB of our product.
I want to clear this value when the block is released in one of the ways:
1. Automatic release after blocking time.
2. Using the `delete` function.

I would suggest adding the option to pass a callback function to the `RateLimiterMemory` settings.

**Comment by animir** [comment]
@shneor521 Why do you keep additional value in your DB? Could you rely on rate limiter instead?

Feel free to implement `RateLimiterMemory` option for callback.

**Comment by shneor521** [comment]
Sorry for the delay.

I trust the rate limiter (:

If there is a blockage, I need to disable some features in our system.
If the blockage is released, I need to enable them.

I'll try to find time to add it here.

Anyway, I just wrote some wrapping function, which performs manual unblocking with the actions I need.

**Comment by animir** [comment]
@shneor521 Feel free to re-open the issue, if/when you are going to work on `onBlockReleased` feature.
