### ISSUE TITLE
DeprecationWarning with MongoDB (mongodb package v3.6.11)

### ISSUE THREAD

**Issue by smallbzleads** [animir/node-rate-limiter-flexible#132]
I'm recieving this deprecation error when using the mongo driver.

[MONGODB DRIVER] DeprecationWarning: collection.findOneAndUpdate option [returnOriginal] is deprecated and will be removed in a later version.

**Comment by animir** [comment]
@smallbzleads hi, what version of `rate-limiter-flexible` and mongo driver do you use?

**Comment by smallbzleads** [comment]
Hello, 

I'm using "rate-limiter-flexible": "2.3.0" and using  "mongoose": "^5.13.8"

**Comment by animir** [comment]
@smallbzleads If you update mongoose to the latest, you'll get deprecation warning removed. [This condition](https://github.com/animir/node-rate-limiter-flexible/blob/master/lib/RateLimiterMongo.js#L172) would work in case you get latest mongoose.

If you can't update mongoose to the latest, you could try to find exact version, when deprecation is added and improve mongoDB driver version check in [the condition](https://github.com/animir/node-rate-limiter-flexible/blob/master/lib/RateLimiterMongo.js#L172).`mongoose: 5.13.8` depends on `mongodb: 3.6.11`.

**Comment by smallbzleads** [comment]
Oky thank you!
