### ISSUE TITLE
node-redis v4 ReplyError: ERR Error running script

### ISSUE THREAD

**Issue by Feuerhamster** [animir/node-rate-limiter-flexible#133]
Hello, I got a weird exception after implementing `RateLimiterRedis` like in your wiki: https://github.com/animir/node-rate-limiter-flexible/wiki/Redis

Here is the exception I got:
```
ReplyError: ERR Error running script (call to f_a1de965f42e177aa339706bd580f049065eca79a): @user_script:1: @user_script: 1: Lua redis() command arguments must be strings or integers
```

Here is my code:
```js
async consume(ip) {
    if (!this.limiter) return;

    let res = false;

    try {
        res = await this.limiter.consume(ip);
    } catch (e) {
        if (e instanceof Error) {
            console.log("RATE LIMITER ERROR:", e.message);
        } else {
            return false;
        }
    }

    return res;
}
```

**rate-limiter-flexible version:** 2.3.1
**redis version:** 4.0.0-rc.2

**Comment by animir** [comment]
@Feuerhamster Hey, could you console log or debug `ip` variable? Wonder if it is string or number.

**Comment by Feuerhamster** [comment]
![image](https://user-images.githubusercontent.com/38376566/135750320-79d98d06-6b08-49c6-9a54-8b2bfa00175e.png)

Maybe is `RateLimiterRedis` only compatible with the `redis` node module version 3 and not the new version 4?

**Comment by animir** [comment]
@Feuerhamster May be. Is it released already? As I see there is release candidate `4.0.0-rc.2`. Anyway, let us know if you find what causes the issue. Thanks.

**Comment by animir** [comment]
In `rate-limiter-flexible` version `2.x` `redis` package v4+ works with `legacyMode` enabled. See [this comment](https://github.com/animir/node-rate-limiter-flexible/issues/155#issuecomment-1069436565) for context.

**Comment by animir** [comment]
`node-redis` is fully supported now. Read more here https://github.com/animir/node-rate-limiter-flexible/wiki/Redis#redis-package
