### ISSUE TITLE
Wait for Rate Limiter Resources to Become Available

### ISSUE THREAD

**Issue by LandonSchropp** [animir/node-rate-limiter-flexible#143]
I'm trying to migrate a small script from limiter and I'm running into a few issues.

My script calls an API that limits requests to 3 per second, so my script needs to stay under that. In order to do so, I'm trying to write a simple batching function that can be called and will automatically limit requests. Ideally, this function will also process its callbacks in order.

``` javascript
import { RateLimiterMemory, RateLimiterQueue } from "rate-limiter-flexible";

function mapWithRateLimiter(array, callback) {
  const memoryLimiter = new RateLimiterMemory({ points: 3, duration: 1 });
  const queueLimiter = new RateLimiterQueue(memoryLimiter, {});

  return Promise.all(array.map(async (item, index) => {
    await queueLimiter.removeTokens(1);
    return callback(item, index);
  }));
}
```

Once this function gets called with the fourth item, the `removeTokens` function rejects. While this makes sense for an API, in my use case I really want it to wait and resolve when a token becomes available. I was able to achieve this with limiter with the following function:

``` javascript
export async function mapWithRateLimiter(array, callback) {
  const limiter = new RateLimiter({
    tokensPerInterval: 3,
    interval: "second"
  });

  return Promise.all(array.map(async (item, index) => {
    await limiter.removeTokens(1);
    return callback(item, index);
  }));
}
```

Is this possible with rate-limiter-flexible?

Thanks!

**Comment by animir** [comment]
@LandonSchropp Hey, As I know, it is possible with `RateLimiterQueue` and your example above should work as expected. What kind of error did you catch there when removed fourth token from `queueLimiter`?

**Comment by LandonSchropp** [comment]
Hey @animir, this is what I get on the fourth item in the array from that example:

```
reject(new RateLimiterQueueError(`Number of requests reached it's maximum ${_this._maxQueueSize}`))
```

<img width="1281" alt="Screen Shot 2021-11-08 at 1 08 17 PM" src="https://user-images.githubusercontent.com/361591/140802646-1735150e-1b98-48ba-9bf4-9ae5498726fc.png">

**Comment by LandonSchropp** [comment]
I can repro this problem with this:

```
await mapWithRateLimiter([ 1, 2, 3, 4 ], (n) => n * n);
```

**Comment by animir** [comment]
@LandonSchropp I see, thanks. You initialise `new RateLimiterQueue(memoryLimiter, {})` with empty options object, as a result `maxQueueSize` option is set to `undefined`. I think, it should be set to default value in this case, but it isn't.

**Comment by LandonSchropp** [comment]
Ah, that makes sense! So as a workaround I can see the `maxQueueSize`. Thanks!
