### ISSUE TITLE
Passenger compatibility 

### ISSUE THREAD

**Issue by axys16** [animir/node-rate-limiter-flexible#147]
Hello,

I've just added the rate limit to my API thanks to your module.

So I've put my API in preprod, and now I've noticed that the server doesn't start. After some investigation, I found the problem.
We use Passenger, which is not compatible with the Node Cluster module.
https://www.phusionpassenger.com/library/walkthroughs/basics/nodejs/fundamental_concepts.html#vs-cluster-module

If I'm not mistaken, this module is used for the "cluster" mode and the "PM2" mode.
Would it be possible to make these 2 modes optional or deactivatable?

**Comment by animir** [comment]
Hey @axys16,

There was a similar question on stackoverflow https://stackoverflow.com/questions/59417341/node-cluster-module-which-is-incompatible-with-passenger
Let me know, if it helps.

**Comment by axys16** [comment]
Hi @animir,

Yes, it works.

```
const RateLimiterRedis = require('rate-limiter-flexible/lib/RateLimiterRedis');
const RateLimiterMemory = require('rate-limiter-flexible/lib/RateLimiterMemory');
```
Thanks for the help !
