### ISSUE TITLE
Combining multiple rate limiters atomically 

### ISSUE THREAD

**Issue by akashround** [animir/node-rate-limiter-flexible#150]
I want to implement an API rate limiter using Redis. On receiving a request, I call rate limiter.consume(), and then await `ratelimiter.get()` to check if limits have crossed or not. While using this in a distributed system, is it possible 2 commands get executed simultaneously for `consume`, and even though the counters are incremented atomically for both, both threads get the updated value of the counter? for example, if the limit is 100, and the current count is 99, and 2 requests come in, where both the `consume` functions are executed simultaneously, and the counter becomes 101. now both `get` functions receive 101 as counter value, and therefore reject both the requests, but 1 of them should have been allowed. Am I missing something? 

Also, I wanted to create rate limiter having limits for per sec, per minute, per hour, and per day. Currently, I implemented this by creating 4 instances of `RateLimiterRedis` with different duration and prefix parameters. when a request come in, I call `.consume()` on all the 4 instances and then call `.get()` to get the current status and check if rate limits have crossed or not. But in this I am basically making 4 consume calls and 4 get calls, which is taking the whole time of ~250 ms. Can this be somehow reduced by doing the increment of 4 counters in a single call to redis using redis scripts?

**Comment by animir** [comment]
@akashround Hey, first of all, it is not necessary to call `get` after `consume`. `Consume` method returns an object of `RateLimiterRes` class. Its description can be found in the readme of this package.

Redis script implemented for `rate-limiter-flexible` package doesn't support more than one increment per request. You could fork `master` branch and create your own implementation, if it is crucial.

Btw, how do you make 4 consme calls? Do you make them all async? 250ms is too much for 4 async consume requests and then 4 async get requests.

**Comment by akashround** [comment]
Hey, I am defining the  rate limiter like this - 
```
const apiRateLimiterSec = new RateLimiterRedis({
	redis: redisClient,
	keyPrefix: "api_rate_limiter_sec",
	duration: 1, // Store number for 1 sec since first fail
});
```
I am not including anything for points, as I will be checking the limits for every client separately using consumedPoints.

Now if I use async/await to call assume like this - 
```
let res = await apiRateLimiterSec.consume(APIKey);
```
It blocks and timeouts. So I used it like this instead - 
```
apiRateLimiterSec
		.consume(APIKey)
		.then((rateLimiterRes) => {
			console.log("processing request", rateLimiterRes);
		})
		.catch((rateLimiterRes) => {
			console.log("rate limiting", rateLimiterRes);
		});
```
by using this, the counters are getting incremented, which I can see in the get call, but none of the console statements in the above code are getting printed. so I was not able to access the rateLimiterRes object for some reason. Let me know if I am missing something. Because of this, I was calling get function 4 times, which after some parallelization, is happening in 50-60 ms. This might be an issue of redis instance as well, as in dev env, I am using very basic redis instance.

**Comment by animir** [comment]
@akashround 
> I am not including anything for points

Points option is still set by default. You can set `points` to some huge value and check `consumedPoints` from `rateLimiterRes` instead of using `get` method. In this case a request would never be rate limited until you decide it looking at `consumedPoints` for every client separately.

I hope, this helps.

**Comment by akashround** [comment]
Okay, sounds good. I will try that. Any idea about why it is blocking when using async/await and why I am not able to access rateLimterRes object inside .then() ?

**Comment by animir** [comment]
> Okay, sounds good. I will try that. Any idea about why it is blocking when using async/await and why I am not able to access rateLimterRes object inside .then() ?

Did you cover `await` call by try/catch block? You should be able to access `rateLimterRes` in catch block.
Not sure about `then`, if promise is resolved, there should be some value anyway. Could you double-check this, before we dig dipper?

**Comment by akashround** [comment]
Hey, yes I did cover it with a try/catch block, still couldn't get anything. Also, I just realised I am using async-redis package in place of just redis, so that I can use async/await in our redis code, which doesn't work with normal redis package. could that be a reason for block on .consume() function here? This is how I am initializing the redis client - 
```
const redis = require('async-redis');
export const getRateLimiterClient = () => {
    return redis.createClient({
        port:config.REDIS_PORT,
        host:config.REDIS_HOST,
        password:config.REDIS_PASSWORD,
        enable_offline_queue: false
});
} 
```
could this be a reason?

**Comment by akashround** [comment]
Also, there seems to be some breaking changes with the redis 4.0 release. I am getting this error while trying to call consume - 
```
ReplyError: ERR Error running script (call to f_a1de965f42e177aa339706bd580f049065eca79a): @user_script:1: @user_script: 1: Lua redis() command arguments must be strings or integers
      at parseError (...<repo>/node_modules/redis-parser/lib/parser.js:179:12)
      at parseType (...<repo>/node_modules/redis-parser/lib/parser.js:302:14)
``` 
I checked for the argument of consume function and it is a string. So there might be some issue with this. 
Also, the createClient configuration options have changed. 

here is another change - 
```
The enable_offline_queue configuration option is removed, executing commands on a closed client (without calling .connect() or after calling .disconnect()) will reject immediately
```
Will be great if you can update the docs regarding this

**Comment by animir** [comment]
@akashround 
> could this be a reason?

I don't think, `rate-limiter-flexible` tested with `async-redis` package. most likely, it doesn' work because of `async-redis`.

> there seems to be some breaking changes with the redis 4.0 release

Yes, there an open issue for that https://github.com/animir/node-rate-limiter-flexible/issues/133 You can use `ioredis` instead of `redis` package, until `rate-limiter-flexible` is improved to work with `redis` v4.

> Will be great if you can update the docs regarding this

Thanks, I'll update docs, when we fix compatibility with `node-redis` v4 package.

**Comment by animir** [comment]
@akashround Hey, I hope you solved this issue. I am closing this, feel free to re-open if something pops up.
