### ISSUE TITLE
RateLimiterRedis don't aplly params to define limiters

### ISSUE THREAD

**Issue by brocchirodrigo** [animir/node-rate-limiter-flexible#151]
The middleware of createClient don't initiate RaterLimiterRedis method from param "storeClient". The connection to Redis awaiting action and lost communication during execution.
PS: Information in README to the feature is out of date to RedisClient.

**Comment by animir** [comment]
@brocchirodrigo Hey, what `redis` package and version do you use? Could you share a link with README you're talking about?

**Comment by brocchirodrigo** [comment]
Version "rate-limiter-flexible": "^2.3.6"

In "Usage" of [RateLimiterRedis](https://github.com/animir/node-rate-limiter-flexible/wiki/Redis#ratelimiterredis), the component opt don't use socket or legacyMode. I had to put these options to work and inicialize connector to redis client:

My middleware:

`import { Request, Response, NextFunction } from 'express';
import { RateLimiterRedis } from 'rate-limiter-flexible';
import * as redis from 'redis';

import AppError from '@error/AppError';

export default async function rateLimiter(
  request: Request,
  response: Response,
  next: NextFunction,
): Promise<void> {
  const redisClient = redis.createClient({
    legacyMode: true,
    socket: {
      host: process.env.REDIS_HOST,
      port: Number(process.env.REDIS_PORT),
    },
  });

  await redisClient.connect();

  const rateLimiterDef = new RateLimiterRedis({
    storeClient: redisClient,
    keyPrefix: 'rate-limit',
    points: 20,
    duration: 5,
    blockDuration: 10,
  });

  try {
    await rateLimiterDef.consume(request.ip);
    return next();
  } catch (err) {
    throw new AppError('Too many requests', 429);
  }
}
`

**Comment by animir** [comment]
@brocchirodrigo What `redis` package version do you use?

**Comment by brocchirodrigo** [comment]
"redis": "^4.0.1",

**Comment by animir** [comment]
@brocchirodrigo We faced some issues with `redis` v4.x before. Please, use previous version of `redis` package.
If you fix `RateLimiterFlexible` to work with `redis` version 4, please, create a PR with changes.
