### ISSUE TITLE
RateLimiterMemory: clearExpiredByTimeout

### ISSUE THREAD

**Issue by tomjez** [animir/node-rate-limiter-flexible#152]
We are using the `RateLimiterMemory` in production with quite a lot of different keys. It looks like the memory footprint, while being fine when the application starts up, seems to increase permanently over time.
Thus we are wondering if there is anyway to clean up expired keys after a while. Is there a specific reason why the option `clearExpiredByTimeout` is not available for `RateLimiterMemory`?

**Comment by LGmatrix13** [comment]
I am interested in knowing a solution for this as well

**Comment by animir** [comment]
@tomjez @LGmatrix13 Hi, `RateLimiterMemory` doesn't have the `clearExpiredByTimeout` option as it is in the nature of this limiter. `RateLimiterMemory` sets timeouts to delete a key depending on your limiter's options.

Could you provide more details on how many keys you have and how fast memory footprint grows?

**Comment by tomjez** [comment]
Hi @animir, thanks for the quick reply. So do I understand correctly that if a non-zero duration is set, the expired keys are automatically deleted?

We have around 16 different rate limiters, most of which have a duration of 60 seconds. No special GC options set. 

I'd expect ~100k different keys per day. Actually we have less keys in memory, it's only a few hundred, so I guess the timeout is working fine. Memory usage is increasing by a few MBs per hour, but I then the cause must be something else. If it does turn out to have something to do with the RateLimiterMemory, I'll come back with more information.
