### ISSUE TITLE
Performance of multiple calls to consume

### ISSUE THREAD

**Issue by ob6160** [animir/node-rate-limiter-flexible#157]
First off, thanks for making this great library!

I'm doing a spike right now to see if it's suitable for a project at work.  At a high level, we would like to achieve something along these lines:

```typescript
// Make buckets to rate limit by ip, username, and a global rate limiter for the whole route:
const rateLimitIpKey = `signin-${sha256(req.ip)}`;
const rateLimitUsernameKey = `signin-${sha256(username)}`;
const rateLimitGlobalKey = `signin-global`;

// Allow points to be consumed in an order of precedence only if the previous rate limit is not reached
// This is so that a single user is stopped from being able to consume all of our global tokens and execute a DOS attack
const rateLimitedIp = await redisLimiter.consume(rateLimitIpKey, 1);

// Check that the ip limit has not been reached. If it hasn't consume a token from the username check
const rateLimitedUsername = checkNotReachedLimit(rateLimitedIp) && await redisLimiter.consume(rateLimitUsernameKey, 1);

// Check the username limit has not been reached. If it hasn't consume a token from the global check
const rateLimitedGlobal = checkNotReachedLimit(rateLimitedUsername) && await redisLimiter.consume(rateLimitGlobalKey, 1);

// ... application code continues 
```

The main concern I have with this approach is the three calls to `consume` not being very efficient, especially as for most users we'll be making all three calls to `consume`.

Is something happening behind the scenes to batch requests with pipelining or would this approach simply not be sustainable for a high request rate?

**Comment by animir** [comment]
@ob6160 Hey, thank you.

While the idea to make 2, 3 or more calls to Redis in a batch is worth considering sometimes, especially on dozens thousands rpm, there is no need in that in common scenario. Redis is scaled pretty well and doing many lightweight requests fits into that brilliantly. You always get the idea how more of Redis performance you need if traffic doubles, triples, etc.

`rate-limiter-flexible` doesn't send requests in a batch, every consume call results to at least one request to a server.
I hope, this helps.

**Comment by ob6160** [comment]
thanks! I think we're going to have to roll a custom solution as we have a pretty high volume of traffic
