### ISSUE TITLE
Invalid SQL Syntax

### ISSUE THREAD

**Issue by marbuser** [animir/node-rate-limiter-flexible#16]
Hey there,

I recently started using your package and it works pretty well. However, after the server has been on for about 5–10 mins, it crashes due to invalid SQL syntax. It should be noted I'm using Sequelize.

`Executing (default): DELETE FROM dashboard.rateLimiter WHERE expire < ?`

My `rateLimiter` middleware function is shown below;
```js
import { RateLimiterMySQL } from 'rate-limiter-flexible';

import { sequelize } from '../models';

const rateLimiter = new RateLimiterMySQL(
  {
    storeClient: sequelize,
    tableName: 'rateLimiter',
    points: 10,
    duration: 2,
  },
  err => {
    if (err) throw new Error(`Unable to connect to start Rate Limiter \n ${err}`);
  }
);

export default (req, res, next) => {
  rateLimiter
    .consume(req.connection.remoteAddress, 2)
    .then(() => {
      next();
    })
    .catch(() => {
      res.status(429).send('You are sending too many requests.');
    });
};
```

Hopefully you can provide a solution. :)

**Comment by animir** [comment]
@marbuser Hi, I've fixed this bug.
version `0.22.1` published.

**Comment by marbuser** [comment]
> @marbuser Hi, I've fixed this bug.
> version `0.22.1` published.

Hey @animir ,

Thanks for this. I will give it a check tomorrow morning and make sure it's all working properly! :)

**Comment by marbuser** [comment]
@animir 

Appears to be working correctly now! Thanks! :)
