### ISSUE TITLE
Perfomance of Queue getting large

### ISSUE THREAD

**Issue by jonnyfux** [animir/node-rate-limiter-flexible#160]
Hi, 

really love the project! We are using a RateLimiterQueue in memory on a node js server. So users can make 10 requests per second and anything above is queued and processed later. That all works fine. We are just unsure what value to set the max queue size to. 

Do you have any idea or benchmark of the performance of the queue size when it grows?

So e.g. what happens if thousands of requests are stored in the queue?

**Comment by animir** [comment]
@jonnyfux Hey, thank you!

I have never used `RateLimiterQueue` with queue size more than a couple of hundreds. I don't see any performance issues with queue size of thousands or dozens of thousands requests, especially in memory. Timers are quite optimised in Node.js.

Note, if your Node.js app crashes, `RateLimiterQueue` with memory limiter looses all queued requests.

I hope this helps.

**Comment by animir** [comment]
@jonnyfux How is it going?

**Comment by jonnyfux** [comment]
Hi @animirr , 

sorry for the late reply. We implemented a queue with a max Size of 5000. We had pretty high traffic today and we didn't see any performance problems. So as you said, it looks like there is no problem with a big queue size :)

**Comment by animir** [comment]
@jonnyfux Thank for the reply 👍
