### ISSUE TITLE
AWS Lambda: clearExpiredByTimeout seems not work with mysqlRateLimiter

### ISSUE THREAD

**Issue by nouhab** [animir/node-rate-limiter-flexible#163]
the expired keys are not deleted from mysql database,  

const opts = {
  storeClient: pool,
  dbName: 'middle_users',
  tableName: 'rate_limiting', // all limiters store data in one table
  points: process.env['RATE_LIMITER_POINTS'], // Number of points
  duration: process.env['RATE_LIMITER_DURATION_SECOND'], // Per second(s)
  blockDuration: process.env['RATE_LIMITER_BLOCK_DURATION_SECOND'],
  clearExpiredByTimeout :true
  

};

**Comment by animir** [comment]
@nouhab Hey, it should delete all keys expired more than one hour ago every 5 minutes. Could you confirm that even after 65 minutes expired rows are not deleted?

**Comment by nouhab** [comment]
yes i can confirm, keys used yesterday are not deleted until today. i have a key with expired ='1646848363002'
my table contains: 
'1v3tmy9thd/dev/POST/policies/eligibility:2a155b96-6eb7-45e4-a8a2-fda8c53bf33c', ' 8', '1646848363002'

**Comment by nouhab** [comment]
@animar it a table an aurora table in aws , but i have a localhost table and it do not work.
const pool =  mysql.createPool({
  connectionLimit : 150,
  host: process.env['ECLAIMS_DB_URL'],
  user: process.env['ECLAIMS_DB_USERNAME'],
  password: process.env['ECLAIMS_DB_PASSWORD']
});

**Comment by animir** [comment]
@nouhab Could you share table schema (structure) with data types for `points` and `expire` columns?

**Comment by nouhab** [comment]
-- MySQL dump 10.13  Distrib 8.0.28, for Win64 (x86_64)
--
-- Host: localhost    Database: middle_users
-- ------------------------------------------------------
-- Server version	5.7.12

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!50503 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
SET @MYSQLDUMP_TEMP_LOG_BIN = @@SESSION.SQL_LOG_BIN;
SET @@SESSION.SQL_LOG_BIN= 0;

--
-- GTID state at the beginning of the backup 
--

SET @@GLOBAL.GTID_PURGED=/*!80000 '+'*/ '';

--
-- Table structure for table `rate_limiting`
--

DROP TABLE IF EXISTS `rate_limiting`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `rate_limiting` (
  `key` varchar(255) CHARACTER SET utf8 NOT NULL,
  `points` int(9) NOT NULL DEFAULT '0',
  `expire` bigint(20) unsigned DEFAULT NULL,
  PRIMARY KEY (`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `rate_limiting`
--

LOCK TABLES `rate_limiting` WRITE;
/*!40000 ALTER TABLE `rate_limiting` DISABLE KEYS */;
INSERT INTO `rate_limiting` VALUES ('arn:aws:execute-api:eu-central-1:933051338512:1v3tmy9thd/dev/POST/policies/eligibility:71fb8368-ac78-40e6-ae7d-d3f13d278574',6,1646931712492),('arn:aws:execute-api:eu-central-1:933051338512:1v3tmy9thd/dev/POST/policies/eligibility:ac8e7f56-2148-4399-b8f5-c8ea9d32ea6f',2,1646930464928);
/*!40000 ALTER TABLE `rate_limiting` ENABLE KEYS */;
UNLOCK TABLES;
SET @@SESSION.SQL_LOG_BIN = @MYSQLDUMP_TEMP_LOG_BIN;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2022-03-11  9:47:22

**Comment by animir** [comment]
@nouhab thanks. I see in your options the table name is `ratelimiting`, but in this dump it is different `rate_limiting`.

**Comment by nouhab** [comment]
No i just change the table name from my options and delete ratelimiting table

**Comment by animir** [comment]
@nouhab If you change table name or you have not running your project locally, expired rows won't be removed. It works only, if your server is constantly running. Could you try to run it locally for more than 65 minutes and with updated table name?

**Comment by nouhab** [comment]
i already do that, Do you not think it s a problem of local time beacause i notice that some rows are deleted after more than 24 hours

**Comment by animir** [comment]
@nouhab No, `Date.now()` which is used there works in UTC always.

**Comment by nouhab** [comment]
i have to notice that run my rateLimter in an aws environnement with a lambda function.

**Comment by animir** [comment]
@nouhab This is interesting. In this case it would never call a function to clear expired documents. If that function would be called during the start, it could fix the issue.

**Comment by nouhab** [comment]
ok i can call the clearExpired method but why it will never call a function to clear expired documents?

**Comment by animir** [comment]
@nouhab It is not ready for lambda out of the box. It is supposed to work on the server 24/7, so it would delete documents in about 1 hour, but it never happens in aws lambda environment. I'll updated docs for your case soon. Thank you.

**Comment by animir** [comment]
@nouhab I updated docs. Were you able to make it work?

**Comment by nouhab** [comment]
Yes , i make it work by adding and event to my lambda function and that call the clearExpired function

**Comment by animir** [comment]
Ok, nice. I am closing this issue.
