### ISSUE TITLE
Use with token saved in db

### ISSUE THREAD

**Issue by albertorizzi** [animir/node-rate-limiter-flexible#168]
I don't understand if this library allow to check rate limit using token saved in db, for example passed by Authorization field in API request.

Thank you

**Comment by albertorizzi** [comment]
Ok Thank you @animir, I try to implement one of the example provide!

**Comment by albertorizzi** [comment]
So, for my problem I think that this [example](https://github.com/animir/node-rate-limiter-flexible/wiki/Overall-example#authorized-and-not-authorized-users) it's correct form me. I check if the token is present in DB and then I use the id of the Authorization user like this snippet `const key = req.userId ? req.userId : req.ip;`

**Comment by animir** [comment]
@albertorizzi If it satisfy your requirements, then it is correct.

**Comment by animir** [comment]
I'm closing this, feel free to open a question in https://github.com/animir/node-rate-limiter-flexible/discussions/categories/q-a, if you have one.
