### ISSUE TITLE
Setting up a memory limiter with fewer points then .set(), results in negative remaining value

### ISSUE THREAD

**Issue by MiniKraken-Team** [animir/node-rate-limiter-flexible#172]
Hey,

Was trying to add the memory limiter (and pg,mysql and redis limiter) to a project.
But when writing my tests I saw a small discrepancy between the result of the memory limiter and the other ones.
When you create a new memory limiter with let's say 5 points, And we use the .set() api to set a key to 10 points.
When getting the response of a .get() it shows the "remaining" as -5 while for the other limiters (mentioned above) it results in 0.

Thanks In Advance

**Comment by MiniKraken-Team** [comment]
Created a pr for this

**Comment by animir** [comment]
@MiniKraken-Team 👍 Published to npm in version `2.3.8`.
