### ISSUE TITLE
Cannot read properties of null (reading 'points') on Mongoose client

### ISSUE THREAD

**Issue by arthursb2016** [animir/node-rate-limiter-flexible#174]
So I'm getting this error `Cannot read properties of null (reading 'points')` when the given key is still not present on my MongoDB. After the first limit check, when the first record is written, the logic works fine.

My code looks like:

```
const mongoose = require('mongoose');
const { RateLimiterMongo } = require('rate-limiter-flexible');
const i18n = require('i18n')

// Creates the sender rate limit protection
const rateLimiterMongo = new RateLimiterMongo({
  storeClient: mongoose.connection,
  points: 1,
  duration: 60 * 60
});

// Checks if the sender ip can send the email
const checkSendLimit = ({ ip, limit, hours }, template) => {
  return new Promise((resolve, reject) => {
    if (!ip || !template) {
      reject({ message: i18n.__('MESSAGER.MISSING_SEND_DATA') })
    }
    const limitKey = `${ip}-${template}`
    rateLimiterMongo.points = limit || 3
    rateLimiterMongo.duration = (hours || 1) * 60 * 60
    rateLimiterMongo.consume(limitKey, 1)
      .then((obj) => {
        resolve(obj)
      }).catch((err) => {
        // ...set custom headers
        reject({
          message: err.message || i18n.__('MESSAGER.SEND_LIMIT'),
          customHeaders,
        })
    })
  })
}

// Sends an email message through the SMTP provider
const sendEmail = async (sendLimit, { to, subject, template, values }) => {
  try {
    await checkSendLimit(sendLimit, template)
   // ...do stuff
```

The error seems to be coming from `lib/RateLimiterMongo.js` line 124:

```
  _getRateLimiterRes(rlKey, changedPoints, result) {
    const res = new RateLimiterRes();

    let doc;
    if (typeof result.value === 'undefined') {
      doc = result;
    } else {
      doc = result.value;
    }

    res.isFirstInDuration = doc.points === changedPoints; // line 124 <<<<<
    ...
```

My package version is `"rate-limiter-flexible": "^2.3.8"`

**Comment by animir** [comment]
Most likely the same as https://github.com/animir/node-rate-limiter-flexible/issues/161

**Comment by arthursb2016** [comment]
Thank you for the fast repply, I'm checking it.

**Comment by arthursb2016** [comment]
Indeed it was the same thing, thank you @animirr 

Your comment there was 100% correct: 

> Hey. It is not about this package, it is about how you structure your code...

In my specific situation I just had to place the RateLimiter constructor inside the `checkSendLimit` function:

```
// Checks if the sender ip can send the email
const checkSendLimit = ({ ip, limit, hours }, template) => {
  // This has to be inside the function in my cenario
  const rateLimiterMongo = new RateLimiterMongo({
    storeClient: mongoose.connection,
    points: 1,
    duration: 60 * 60
  });
  // ...check the sendl imit
```

**Comment by nirmal-patel-s** [comment]
> Indeed it was the same thing, thank you @animirr
> 
> Your comment there was 100% correct:
> 
> > Hey. It is not about this package, it is about how you structure your code...
> 
> In my specific situation I just had to place the RateLimiter constructor inside the `checkSendLimit` function:
> 
> ```
> // Checks if the sender ip can send the email
> const checkSendLimit = ({ ip, limit, hours }, template) => {
> 
>   // This has to be inside the function in my cenario
>   const rateLimiterMongo = new RateLimiterMongo({
>     storeClient: mongoose.connection,
>     points: 1,
>     duration: 60 * 60
>   });
>   // ...check the sendl imit
> ```
as mentioned by @arthursb2016,  
one should export a function which can return the RateLimiterMongo instance.
