### ISSUE TITLE
Migration from node-rate-limiter package: Using RateLimiterQueue with BurstyRateLimiter?

### ISSUE THREAD

**Issue by dt-atkinson** [animir/node-rate-limiter-flexible#175]
Hi

In the documentation for BurstyRateLimiter it claims `All limiters from this package can be used for BurstyRateLimiter creation`. However, if you try to construct one with RateLimiterQueue it fails because it doesn't adhere to the necessary interface.

I am trying to migrate from TokenBucket from the https://github.com/jhurliman/node-rate-limiter package. This behaves in such a way that you can burst but also has an outstanding request queue so you can `await` on the calls for the bucket to refill.

I want to take the FIFO logic & promise awaits from RateLimiterQueue but the burst of BurstyRateLimiter.

Without writing a wrapper this currently is not achievable.

KR

**Comment by animir** [comment]
@dt-atkinson Hey, that's true, all limiters can be used. The thing is Queue is more sophisticated limiter with different purpose and can't be used for `BurstyRateLimiter`.

Language in this and `limiter` packages is a little bit confusing. In `rate-limiter-flexible` points are consumed not burst. Bursty limiter provides advanced way of consuming points with burst allowance. For example, it may re-fill with 2 points every second plus it provides burst allowance for 5 points per 10 seconds. Read more on BurstyRateLimiter [here](https://github.com/animir/node-rate-limiter-flexible/wiki/BurstyRateLimiter).

You don't need `BurstyRateLimiter`, if you want to migrate to this package. Just use `RateLimiterQueue` and that's it. Read this [article](https://github.com/animir/node-rate-limiter-flexible/wiki/RateLimiterQueue#migration-from-limiter) about migration.

If you still want something more advanced, you can create `RateLimiterQueue` with `BurstyRateLimiter` under the hood like this:
```js
const burstyLimiter = new BurstyRateLimiter(
  new RateLimiterMemory({
    points: 2,
    duration: 1,
  }),
  new RateLimiterMemory({
    keyPrefix: 'burst',
    points: 5,
    duration: 10,
  })
);

const limiterQueue = new RateLimiterQueue(burstyLimiter, {
  maxQueueSize: 100,
});
```

**Comment by dt-atkinson** [comment]
I have read the article - it only covers the use case of migrating RateLimiter not TokenBucket (there are two classes in the project).

Thank you for your insight I will look at your solution

**Comment by dt-atkinson** [comment]
Can RateLimiterQueueError be exported from the package so I can catch it?

**Comment by animir** [comment]
@dt-atkinson I think, it can be.
There is an example in docs [here](https://github.com/animir/node-rate-limiter-flexible/wiki/RateLimiterQueue#when-is-removetokens-method-rejected)

**Comment by animir** [comment]
@dt-atkinson Did `RateLimiterQueue` based on `BurstyRateLimiter` satisfied your needs? With what did you end up the migration?

**Comment by dt-atkinson** [comment]
I actually ended up not migrating at this point due to actually needing TokenBucket functionality.

Having a constant drip feed which is usable for queued requests as they wait in a timely manner was required (which your solution provides).

However, I also wanted the bucket backfill to happen at the same rate for burst. This wasn't possible with BurstyRateLimiter because it would add a large chunk of tokens at a designated time rather than drip feed as a token bucket would do.

These are purely system design considerations for my application - whereby I want to be able to have a steady rate after burst is used up. Then after points are stopped from being consumed the drip is used to restock the burst.

I also required the ability to be able to clear the queues out programatically which I had yet to investigate.

**Comment by animir** [comment]
> This wasn't possible with BurstyRateLimiter because it would add a large chunk of tokens at a designated time rather than drip feed as a token bucket would do.

I understand you need it to be re-filled in small chunks. You could try to create a limiter with long duration like 14 days and re-fill 1 point every second with  `setTimeout` using [reward](https://github.com/animir/node-rate-limiter-flexible/wiki/API-methods#ratelimiterrewardkey-points--1) function, but not sure if it is worth it.
