### ISSUE TITLE
Typo on the InsuranceStrategy wiki page

### ISSUE THREAD

**Issue by dhersam** [animir/node-rate-limiter-flexible#181]
I noticed a typo on the [InsuranceStrategy wiki page](https://github.com/animir/node-rate-limiter-flexible/wiki/Insurance-Strategy)

RedisLimiterMemory -> RateLimiterMemory

On line 2, instead of:

`const { RateLimiterRedis, RedisLimiterMemory } = require('rate-limiter-flexible');`

It should be:

`const { RateLimiterRedis, RateLimiterMemory } = require('rate-limiter-flexible');`

**Comment by animir** [comment]
@dhersam Hey, thank you. It is fixed now.
