### ISSUE TITLE
Can this lib be used with axios?

### ISSUE THREAD

**Issue by buenofs** [animir/node-rate-limiter-flexible#182]
Just wanted to know if this is possible to be used with Axios, I know there is examples on how to do it with express middlewares, following the same logic with Axios interceptors can be done?

**Comment by animir** [comment]
@buenofs Hey, I don't see why not. You can use any method from this package as you wish. https://github.com/animir/node-rate-limiter-flexible/wiki/API-methods

**Comment by animir** [comment]
Feel free to reopen if you still have questions.
