### ISSUE TITLE
RateLimiterUnion behaviour with one item

### ISSUE THREAD

**Issue by svsool** [animir/node-rate-limiter-flexible#183]
Hi, thank you for this library.

Would it be possible to remove greater than 1 item artificial limit in RateLimiterUnion or may I ask what was the reason to introduce it in the first place?

Having a consistent behaviour with one or more items is beneficial because we don't need to introduce branching logic handling such cases separately.

**Comment by animir** [comment]
@svsool Hey, thanks.

I think, it can work with one limier as it is, but at least one limiter should be set.
You could change that condition check, if you wish.
