### ISSUE TITLE
RateLimiterRedis: track redis client connection state for faster response

### ISSUE THREAD

**Issue by dmozgovoi** [animir/node-rate-limiter-flexible#184]
In case of RateLimiterRedis if underlying client connection is closed, limiter still trying to call Lua script before falling back to insuranceLimiter. As result, very long response time even with in-memory insuranceLimiter.

Possible solution: track state of redis client connection and immediately throw Error to use insuranceLimiter until connection is established again.

**Comment by animir** [comment]
@dmozgovoi Hey, thank you. Not sure about implementation details. Do you have some example or suggestion, how it could be implemented? Would you like to prepare a PR for that?

**Comment by dmozgovoi** [comment]
Ok, I have an idea and I will prepare PR
