### ISSUE TITLE
Waiting after blocking ip

### ISSUE THREAD

**Issue by samartsevigor** [animir/node-rate-limiter-flexible#185]
I implemented such a middware, but if my points are over, then it does not give an error, but freezes for 10 seconds.

```
export const rateLimiterMiddleware = async (req: Request, res: Response, next: NextFunction) => {
  try {
    await rateLimiter.removeTokens(1);
    next();
  } catch (err) {
    if (err instanceof Error) {
      res.status(400).end();
    } else {
      res.status(429).send('Too Many Requests');
    }
  }
};
```

And I have one more question, there are several instances on my server, and the number of points is doubled, will RateLimiterQueue help me with my problem ?

**Comment by animir** [comment]
@samartsevigor Could you share full code related to `rateLimiter` creation?

**Comment by animir** [comment]
Closing this. Feel free to reopen if needed.
