### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by TomMettam** [animir/node-rate-limiter-flexible#186]
https://github.com/animir/node-rate-limiter-flexible/blob/af6dfd420fa1b2acd1cb7e3ef9634b5e90c61c67/lib/RateLimiterCluster.js#L152

This throws an unhandled exception out to node, which crashes the application.

Can we just ignore invalid messages instead, so that this module can be used with other things which communicate via cluster messages?

**Comment by animir** [comment]
@TomMettam Could you explain why do you need a new msg type?
There is a condition on top of that function, which makes sure no messages from other package would ever be processed with RateLimiterCluster code.
https://github.com/animir/node-rate-limiter-flexible/blob/af6dfd420fa1b2acd1cb7e3ef9634b5e90c61c67/lib/RateLimiterCluster.js#L126

It should never reaches that switch with exception.

**Comment by TomMettam** [comment]
(FYI - I'm sending messages using "type" as a key)

**Comment by animir** [comment]
@TomMettam `channel` value can not be undefined. It is constant set to `rate_limiter_flexible` string. Could you also share the whole error with stack trace?

**Comment by TomMettam** [comment]
I've already forked the repo and changed the exception to a "return false", but if I have time later i'll investigate further.

In general, though, you shouldn't throw exceptions back to node..

**Comment by animir** [comment]
@TomMettam In this case, it is a sign of something going on wrong. An application shouldn't work if some other code uses the same channel as this package.

**Comment by animir** [comment]
I am closing this issue. Feel free to re-open if you wish to investigate the exception togeter.
