### ISSUE TITLE
Example of inMemoryBlockOnConsumed and inMemoryBlockDuration

### ISSUE THREAD

**Issue by blueberry6401** [animir/node-rate-limiter-flexible#190]
I'm reading docs and not quite understand those 2 options, especially inMemoryBlockOnConsumed is defined as number.
Can you provide some example about how inMemoryBlockOnConsumed value affect the blocking or how it works?
Thank!

**Comment by animir** [comment]
@blueberry6401 Hi, There are examples [here](https://github.com/animir/node-rate-limiter-flexible/wiki/Overall-example#apply-in-memory-block-strategy-to-avoid-extra-requests-to-store) and [here](https://github.com/animir/node-rate-limiter-flexible/wiki/In-memory-Block-Strategy)

**Comment by animir** [comment]
Feel free to re-open if you still have some questions.
