### ISSUE TITLE
Expose `keyPrefix` to `RateLimiterRes` if available

### ISSUE THREAD

**Issue by lxcid** [animir/node-rate-limiter-flexible#193]
When we use multiple rate limiter together, and `consume()` fails and throw `RateLimiterRes`, we are unable to determine which rate limiter is failing. as the interface of `RateLimiterRes` is too generic.

If the `keyPrefix` is forwarded `RateLimiterRes`, we can then identify which rate limiter is failing.

**Comment by animir** [comment]
@lxcid Could you provide code example how do you use multiple rate limiters? [RateLimiterUnion](https://github.com/animir/node-rate-limiter-flexible/wiki/RateLimiterUnion) probably fits your needs.
