### ISSUE TITLE
PgBouncer Error: prepared statement already exists

### ISSUE THREAD

**Issue by harryn** [animir/node-rate-limiter-flexible#195]
I am getting a following error: `You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection: error: prepared statement "public.rate_limiter:undefined" already exists`.

It seems that the rejection happens during the creation of the limiter:
```js
const rateLimiterHours1 = new RateLimiter.RateLimiterPostgres({
  storeClient: pool,
  points: 250,
  duration: 3600,// 1 hour
  tableName: 'public.rate_limiter',
  keyPrefix: 'limiter_hours_1',
});
```

And I consume this limiter only in one place where it has a catch:
```js
rateLimiterUnion.consume(ip) // union of 1 RateLimiterMemory and 1 RateLimiterPostgres
  .then(_limiter => {
    next();
  })
  .catch((_err) => {
    console.log(_err)
    next(new HTTP429Error())
  });
```

Please feel free to let me know if if I can provide some additional details!

**Comment by animir** [comment]
@harryn Hi, could you provide a code where you create `pool` of connections? Also, postgres package and version. Thanks.

Most likely, it this error related to table creation statement https://github.com/animir/node-rate-limiter-flexible/blob/master/lib/RateLimiterPostgres.js#L133. I guess, it tires to create a table twice and registers the same statement also.

**Comment by harryn** [comment]
@animir Hi!
Here's the creation of `pool`:
```js
export const pool = new Pool({
  host: 'localhost',
  user: 'postgres',
  password: 'postgres',
  database: 'postgres',
  port: 5432,
  max: 25,
  idleTimeoutMillis: 30000,
  connectionTimeoutMillis: 9000,
});
```
I am using the `pg` (`node-postgres`) package. Version 8.0.3.

The table is actually there, but seems the error starts appearing after the first restart of the application. After waiting for some time (cache?) I can start the application again, but occasionally consume triggers: `limiter_hours_1': error: prepared statement "public.rate_limiter:rlflx-upsert" does not exist`.

**Comment by animir** [comment]
@harryn Hm, it looks like prepared statements are disabled on your DB. Could you check that?

**Comment by harryn** [comment]
@animir I'm not exactly sure how to check it, but will investigate.

If it helps, then I am using PgBouncer.
Also, some queries must go through, because the table gets created.
Also also, when the initialization doesn't fail then `consume` sometimes works, sometimes doesn't. Which means that the `public.rate_limiter` has rows. But `consume` gets quite often these `rlflx-upsert` errors (either prepared statement **doesn't exists** or **already exists**).

Sorry, if the description is confusing - just I don't understand 100% yet the exact conditions which result in these prepared statement errors.

**Comment by animir** [comment]
@harryn Thanks. I found a lot of similar issues with PGBouncer on the internet. Try `pg prepared statement error` or `pgbouncer prepared statement already exists` search. I don't share any here, since you better know what exactly should be checked.

**Comment by animir** [comment]
@harryn Hi, any progress on fixing this issue?

**Comment by harryn** [comment]
@animir Hi! Couldn't figure out the reason why prepared statements had issues. Did a workaround so that the limiter would not use prepared statements. Has been working flawlessly so far.

**Comment by animir** [comment]
Ok, thanks,
I am closing this issue for now. I think, it is not related to this package.
Feel free to reopen.
