### ISSUE TITLE
RateLimiterRedis:  Error "Lua redis lib command arguments must be strings or integers"

### ISSUE THREAD

**Issue by miertschink** [animir/node-rate-limiter-flexible#198]
I am using RateLimiterRedis and as soon as `consume` is called I get the error

```
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[ErrorReply: ERR Lua redis lib command arguments must be strings or integers script: a1de965f42e177aa339706bd580f049065eca79a, on @user_script:1.]
```

After a long time I figured out, **that it works fine when I set `legacyMode: true` in the clientOptions**
```
const redisClient = createClient({
    url: redisUrl, 
    legacyMode: true
});
```

Any idea why this is needed?

This is how I use it
``` 
import { createClient } from 'redis';
import { RateLimiterRedis } from 'rate-limiter-flexible';


const redisClient = createClient({url: redisUrl});
await redisClient.connect();
  
const MyRateLimiter = new RateLimiterRedis({
    storeClient: redisClient,
    keyPrefix: `myPrefix`,
    points: 1,
    duration: 60
  });
```
package.json

```
 "rate-limiter-flexible": "^2.4.1",
 "redis": "^4.5.1"
 ```

**Comment by miertschink** [comment]
Might be due to breaking changes from redis 3 to 4 ?
https://github.com/redis/node-redis/blob/master/docs/v3-to-v4.md

**Comment by miertschink** [comment]
as mentioned there is already a PR to support redis v4

**Comment by dilshans2k** [comment]
which versions of redis client and node-rate-limiter-flexible to use to make them work?
I am currently on 
"@node-redis/client": "^1.0.4",
"rate-limiter-flexible": "^2.4.1",

Please help

**Comment by miertschink** [comment]
Try to use to latest version of client and set the legacyMode option when creating it

```
 @redis/client@^1.5.5
 ```
 
 ```
 createClient( {url: ..., legacyMode: true })
 ```
