### ISSUE TITLE
What is right way to get current number of points by key?

### ISSUE THREAD

**Issue by OsoianMarcel** [animir/node-rate-limiter-flexible#2]
Hello,

What is right way to get current number of points by key?
In my opinion, would be great to have a special getter for that.
I want to send remained points via special HTTP header.
At the moment I'm using RateLimiterMemory.

Good job and thank you.

**Comment by OsoianMarcel** [comment]
In my opinion, it's a bad practice to access private properties like this:
```js
rateLimiter._memoryStorage.get(rateLimiter.getKey(req.ip));
```

**Comment by animir** [comment]
Hi @OsoianMarcel 
You can use `rateLimiter.penalty(req.ip, 0)` or `reward` method as workaround
They both return `RateLimiterRes` https://github.com/animir/node-rate-limiter-flexible#ratelimiterres-object
You can get `consumedPoints`  from there

You are free to add the new method `get` to limiter. 
PS: I do have many plans to implement PostgreSQL, Aerospike, Tarantool, LevelDB limiters, so any help appreciated

**Comment by animir** [comment]
Hi @OsoianMarcel 

I've added `get` method to RateLimiterMemory.
It resolves with `RateLimiterRes` https://github.com/animir/node-rate-limiter-flexible#ratelimiterres-object or NULL if key is not set.

**Comment by OsoianMarcel** [comment]
Thank you, I'll contribute to your library (at the moment I'm very busy).
