### ISSUE TITLE
Add JSON method signatures to RateLimiterRes type

### ISSUE THREAD

**Issue by michaeldzjap** [animir/node-rate-limiter-flexible#20]
Would it be possible to add the `toString` and `toJSON` method signatures to the type declaration for `RateLimiterRes`? At the moment _TypeScript_ complains about these two properties not being available on an instance of `RateLimiterRes`.

**Comment by animir** [comment]
@michaeldzjap hi, could you do it? Community would appreciate that.
I don't have time until weekend

**Comment by michaeldzjap** [comment]
@animir I've submitted a PR for this: #21

**Comment by animir** [comment]
@michaeldzjap thanks.
Published with `v0.22.7`
