### ISSUE TITLE
Possibility to slow down requests instead of blocking?

### ISSUE THREAD

**Issue by Thomas-1985** [animir/node-rate-limiter-flexible#201]
Hello

Is there any way (and if so, how) to slow-down requests instead of rejecting it if the maximum amount of points has been consumed for a client?

I mean something like implemented in https://www.npmjs.com/package/express-slow-down

**Comment by animir** [comment]
@Thomas-1985 Hi, there is no built-in method for that. As I understand, slowing down may be easily implemented with `setTimeout`. If maximum amount of points has been consumed, just set timeout for some number of milliseconds. You can even increase that time depending on amount of points consumed.

**Comment by animir** [comment]
@Thomas-1985 Hi, were you able to implement it?

**Comment by Thomas-1985** [comment]
Sadly, no. Maybe you can share a small example? This would be really helpful

**Comment by animir** [comment]
@Thomas-1985 Sorry, I don't have it.

But it should be something like:
```js
async function consumeSlowDown(limiter, ipAddress) {
  try {
    const res = limiter.consume(ipAddress)
    resolve(res) 
  } catch (rej) {
    if (rej instanceof Error) {
          reject(rej)
        } else {
          setTimeout(() => { resolve(rej) }
             , rej.consumedPoints * 100 // More points consumed, longer it waits
          )
        }
   }
}
```

I didn't test it, but you should get the idea.
You could call it like:
```js
await consumeSlowDown(limiter, '127.0.0.1')
```

**Comment by animir** [comment]
@Thomas-1985 Hi, were you able to use suggested method?
