### ISSUE TITLE
High response times with execEvenly: true

### ISSUE THREAD

**Issue by dilshans2k** [animir/node-rate-limiter-flexible#203]
Hi,
I am running load test with various algorithms available and found out, with `execEvenly:true` response times for success cases are very high (over 25s). This is the configuration
```
    this.evenlyRateLimiter = new RateLimiterRedis({
      storeClient: this.redisClient,
      points: 100,
      duration: 60,
      inMemoryBlockOnConsumed: 120,
      execEvenly: true,
    });
```

With `execEvenly:true`, 
![image](https://user-images.githubusercontent.com/67574348/218654461-b4603451-1978-4f25-9388-ec6bf5178a14.png)

Without `execEvenly:true`,

![image](https://user-images.githubusercontent.com/67574348/218654574-b50d0c7d-31ea-409a-b0d1-a61429103f59.png)

**Comment by animir** [comment]
@dilshans2k Hi, have you read [this article](https://github.com/animir/node-rate-limiter-flexible/wiki/Smooth-out-traffic-peaks) on Wiki?

**Comment by animir** [comment]
@dilshans2k In short, if `execEvenly` option is `true` it delays requests specific way. So what you see in your test results is expected.

**Comment by animir** [comment]
Note, I have just added the link to the article about `execEvenly` to the page devoted to [options](https://github.com/animir/node-rate-limiter-flexible/wiki/Options#execevenly).

**Comment by dilshans2k** [comment]
Ok thanks
