### ISSUE TITLE
Make it possible to log when an error occurs

### ISSUE THREAD

**Issue by janmeier** [animir/node-rate-limiter-flexible#205]
We are creating a redis rate limiter, with an in-memory insurance limiter. We would like to be notified whenever a call to redis fails, so we can do something about it :)

The way I've done it for now is to subclass `RateLimiterRedis`:

```ts
class LenusRateLimiterRedis extends RateLimiterRedis {
  _handleError(err, funcName, resolve, reject, key) {
    errorTracker.capture('Error in redis rate limiter', { key, funcName }, err)
    super._handleError(err, funcName, resolve, reject, key)
  }
}
```

This works fine, but since `_handleError` is not part of the ts interface definition we won't be notified if the definition of `_handleError` changes.

My idea would be to either:
* Make `_handleError` (or a similar method) part of the public interface, so we can subclass is properly
* Add an `onError` callback to options
* Emit an `error` event

Whichever option you like most, I would be happy to implement it :)

**Comment by animir** [comment]
@janmeier Hi, this is an interesting case.
While I understand your requirement, there is another way of thinking about it. We should expect Redis isn't able to handle a request in only one case—a connection error.
You could use `redisClient.on('error`, (err) => {})` event to catch and log that error.
If you see some issues with the suggested approach, please describe your case in more detail so that we can discuss it.

**Comment by janmeier** [comment]
>  You could use redisClient.on('error', (err) => {}) event to catch and log that error.

That was my initial though, but it seems the connection error is not being emitted (at least not in ioredis). Related issues https://github.com/luin/ioredis/issues/969 and https://github.com/luin/ioredis/issues/1386

While I agree in principle that we could just handle this on the redis level, there have been no maintainer responses to those issues as far as I can see :/

**Comment by animir** [comment]
@janmeier Hi, have you found a suitable solution for this?

**Comment by shameersheik** [comment]
Some of the errors didnot trigger  redisClient.on('error', (err) => {}) but triggered 

```
reconnectOnError: function (err) {
          logger.info(`Got an error when redis tried to connect: ${err.stack}`);
          return true;
        },
```
