### ISSUE TITLE
DB queries hang when using sequelize/mariadb

### ISSUE THREAD

**Issue by FoxxMD** [animir/node-rate-limiter-flexible#213]
Amazing project! I'm hoping i can get this to work for db persistence...

I'm using sequelize (6.32.1) with a mariadb  (10.10.2-MariaDB-1:10.10.2+maria~ubu2204) connection. This is an existing project with no connection issues to my database.

```js
import {RateLimiterMySQL} from "rate-limiter-flexible";

// sequelize setup already done

const limiter = new RateLimiterMySQL({
                    storeClient: seqDb,
                    storeType: 'sequelize',
                    dbName: 'mtv'
                }, (err) => {
                    if(err) {
                        console.log(err)
                    }
                });
```

limiter executes up until it [tries to create database](https://github.com/animir/node-rate-limiter-flexible/blob/46a218c98b0482f226c46154a3cb37c324bedcf9/lib/RateLimiterMySQL.js#L136) at which point `conn.query(..)` just hangs. No promise rejection, no errors.

The same result occurs if I do not specify `dbName` and if I use a raw [mariadb connection](https://github.com/mariadb-corporation/mariadb-connector-nodejs) instead of sequelize. Mariadb's [client protocol is compatible with MySql](https://mariadb.com/kb/en/mariadb-vs-mysql-compatibility/) so I didn't think using it would be an issue.

I have enabled debug logging for sequelize and can confirm all db statements up until `conn.query()` at which point nothing is logged. Is there anything I can do to debug this further?

**Comment by animir** [comment]
@FoxxMD Hi!

It should call callback function if there is an error during database or table creation. You have it in place. It is weird why you don't see error. Does your code wait enough until database and table created? Could you not run anything, until that callback called without or with error?
Another idea, you could create database manually and set [tableCreated](https://github.com/animir/node-rate-limiter-flexible/wiki/Options#tablecreated) option to true. You could also create table manually. You can find table structure [here](https://github.com/animir/node-rate-limiter-flexible/blob/46a218c98b0482f226c46154a3cb37c324bedcf9/lib/RateLimiterMySQL.js#L157). It would give us more input on the issue.

**Comment by FoxxMD** [comment]
It's occurring because, even though the protocol itself is compatible, the clients `mysql2` and `mariadb` are not. mysql uses `conn.query(sql, vals, cb)` while mariadb returns a promise from `conn.query(sql, vals)`.

Mariadb provides a [callback compatibility library `mariadb/callback`](https://github.com/mariadb-corporation/mariadb-connector-nodejs/blob/master/documentation/callback-api.md) that is _supposed_ to be drop in for `mysql2` but it doesn't seem to be working for me. There's also the issue of sequelize instantiating a connection from `maria`.

I attempted to wrap this in RateLimiterMySQL and can get a connection but 1. its messy and 2. `conn.query` still isn't working for some reason: https://github.com/animir/node-rate-limiter-flexible/commit/11fc9dfe8bbcf0ed748e44e7b226a173e0e283ee

This is also more work then I was expecting to put into this for my existing project -- my project supports mariadb and sqlite databases. I'd like to use this library for agnostic db support for limiters for the project but don't have time to implement a sqlite limiter as well.

It would be better if there was a separate Limiter class for use with Sequelize since then the queries could be abstracted to [Sequelize's query interface](https://sequelize.org/docs/v6/other-topics/query-interface/) so then node-rate-limiter-flexible would support all database it supports -- rather than pulling the raw connection.

I'm going to use redis for now and if I have time I'll see about implementing a true sequelize limiter.
