### ISSUE TITLE
BurstyRateLimiter.get( key ) throws error when key doesn't exist yet

### ISSUE THREAD

**Issue by krazydanny** [animir/node-rate-limiter-flexible#214]
Hi :)

The API documentation says .get( key ) method can return Promise<null> when key does not exists but the BurstyRateLimiter throws the following error instead:

TypeError: Cannot read properties of null (reading 'remainingPoints')
      at BurstyRateLimiter._combineRes (/usr/src/app/node_modules/rate-limiter-flexible/lib/BurstyRateLimiter.js:21:13)
      at /usr/src/app/node_modules/rate-limiter-flexible/lib/BurstyRateLimiter.js:67:19
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      
![Screenshot from 2023-07-26 20-51-40](https://github.com/animir/node-rate-limiter-flexible/assets/22056203/5a0a7322-c89b-4b98-9b66-bec6113265ce)

hope it helps!
Thanks!

**Comment by animir** [comment]
@krazydanny Hey, it was a bug.
I have just fixed it and published patched version `2.4.2` to npm.

Enjoy! :)

**Comment by krazydanny** [comment]
Thanks a lot! :)
