### ISSUE TITLE
Increase blockDuration on next failed attempt

### ISSUE THREAD

**Issue by jhnferraris** [animir/node-rate-limiter-flexible#22]
Hello, great library btw. I just wanna if it is possible to increase the `blockDuration` dynamically on succeeding failures?

Given this config

```
const loginLimiter = new RateLimiterRedis({
  redis: redisClient,
  keyPrefix: 'login:',
  points: 5, // 5 attempts
  duration: 60 * 60 * 24, // within a day
  blockDuration: 60, // 1 min
});
```

I want to set the next `blockDuration` to 5mins if the next rate limit reset was already consumed. 

Just to illustrate:

5 attempts > fail > wait for 1 min > 1 min has passed > 5 attempts > fail > wait for 5mins

Is it possible for this library?

Thanks for the help.

**Comment by animir** [comment]
@jhnferraris Hey, thanks
It is not possible out of the box. 
The main thing here, that it should store number of attempts and in the same time consecutive number of going out of limits.

As I see, you want to protect login endpoint.
There is an [example on wiki](https://github.com/animir/node-rate-limiter-flexible/wiki/Overall-example#login-endpoint-protection), which describes something similar you want to achieve.

If you slightly modify that example, you could achieve desired:
```javascript
const loginLimiter = new RateLimiterRedis({
  redis: redisClient,
  keyPrefix: 'login:',
  points: 5, // 5 attempts
  duration: 60 * 60 * 24, // within a day
});

// Note, I removed built-in blockDuration, we're going to do that manually with `block` method.

const limiterConsecutiveOutOfLimits = new RateLimiterRedis({
  redis: redisClient,
  keyPrefix: 'login_consecutive_outoflimits',
  points: 99999, // we really need just to count
  duration: 60 * 60 * 24 * 90, // Store number for 90 days since first fail
});
```

Logic should be:
1. Consume from `loginLimiter` on failed login
2. If consumed more than 5 per day, `limiterConsecutiveOutOfLimits.get(ipOrUsername)` returns null or N of already consecutive limited days.
3. depending on that N, use `loginLimiter.block(ipOrUsername, numberOfSeconds)`
4. clear on success login if N > 0 `limiterConsecutiveOutOfLimits.delete(ipOrUsername)`

There is also an [article with more examples](https://medium.com/@animirr/brute-force-protection-node-js-examples-cd58e8bd9b8d)

Hope, this helps.

Btw, if you come up with some solution, could you share it here. It may be useful to others. Probably, it could be a new wrapper with increasing block duration, thanks in advance.

**Comment by jhnferraris** [comment]
Thanks for the direction. I'll let you know if I figure out the solution

**Comment by animir** [comment]
@jhnferraris hey, how is it going?

I've added an [example of dynamic block duration](https://github.com/animir/node-rate-limiter-flexible/wiki/Overall-example#dynamic-block-duration) to Wiki

I hope, this helps.

**Comment by jhnferraris** [comment]
Hello @animir, I haven't gotten back on it yet. Thanks for the wiki. I'll check this out. 

Closing this ticket since you provided some direction. Cheers dude!

**Comment by jhnferraris** [comment]
@animir Hello Roman. I had the chance to try out your fibonacci block behavior. It works pretty well. Thanks dude!
