### ISSUE TITLE
Lua Script uses only Write commands and Cannot Scale in a Redis Cluster

### ISSUE THREAD

**Issue by shameersheik** [animir/node-rate-limiter-flexible#222]
https://github.com/animir/node-rate-limiter-flexible/blob/d4e26c0748e9213b5646694f8a3d46db8ba56824/lib/RateLimiterRedis.js#L5

When i went through the Lua script above. I noticed that it doesnot have any Read commands.

It works based on the response of the write command.
`local consumed = redis.call('incrby', KEYS[1], ARGV[1]) \`

In a Redis Cluster, normally read commands go to replica nodes and we would increase the replica nodes to scale to tackle load, 

But here since we only have write commands we wont be able to horizontally scale (write commands are handled by one primary node). Wont this cause problems in the long run by introducing a bottle neck ? 

Steps to reproduce : 
1. I checked a aws elastic cache redis cluster for the get commands metric and its 0.

**Comment by animir** [comment]
@shameersheik Thanks, this is interesting. There is a price for atomic increments. While there are ways to optimize this, this package provides a general solution. It may be not optimal for all use cases.

Do you have any idea, how to improve this Lua script so it can scale on Redis Cluster?

**Comment by shameersheik** [comment]
My idea would be to go from

1. write the data
2. get the data as a response from write
3. check ratelimiter logic 

to

1. read the data - use a get command here
2. Check ratelimiter logic
3. Write the data (use a lua script here)

**Comment by animir** [comment]
@shameersheik It would break atomic increments and may lead to vulnerability to brute-force attacks in some cases and to losing money in other cases.

**Comment by TheGreenCedar** [comment]
Do we need atomic increments if the key is already throttled for the time window?

imo the proposition makes sense as an optimization for when the key has already been throttled in the time window, particularly in the case of a DOS attack, we'd avoid many write calls to Redis if we already know they're throttled and don't need to increment any counters until the end of the time window. Once the time window ends, we can write into redis the increments again.

This would require the different instances of the rate limiter to be synchronized around the time windows though to make sure they're not inaccurate.

**Comment by shameersheik** [comment]
True, I think the tradeoffs would be between stability and speed.

Correctness - 1000 tasks or hosts waiting for a single write 
               - here the data would be correct but it also means it is the same as having one task at a time (here Redis becomes a bottleneck)
               
Speed - 1000 tasks or hosts Not waiting for a single write , but downside is 1000 tasks reading a -1 or +1 data 
               - I think prioritizing speed here is priority since
                  - this lets a service scale and removes the bottleneck.
                  - parallel operations can happen. (I dont want 100 hosts that have the capability to wait for one Redis )
                  - Correctness of data is a question here, but I think Redis will have good replication lag timings to counter this.

**Comment by animir** [comment]
@TheGreenCedar This package provides an option to mitigate DOS attacks. You can read about it here https://github.com/animir/node-rate-limiter-flexible/wiki/In-memory-Block-Strategy.

**Comment by animir** [comment]
@shameersheik While I agree that non-atomic increments are faster, they can't be used everywhere. As I mentioned above this package is used to protect services against brute-force attacks, it is also used to count money-related things for pricing plans. Non-atomic increments can't be used there.

**Comment by animir** [comment]
@shameersheik If you think it would be useful to have non-atomic increments you can create another limiter class and call it `RateLimiterRedisNonAtomic`. It would be great to have it in the package, I think.

**Comment by animir** [comment]
Closing this one. Feel free to reopen if something pops up.
