### ISSUE TITLE
Unable to use table with schema name

### ISSUE THREAD

**Issue by paulsc54** [animir/node-rate-limiter-flexible#226]
Hi there,

We are using your library with the postgres driver and a table defined in a different schema (not public). As introduced by this [commit](https://github.com/animir/node-rate-limiter-flexible/commit/b98a9a504036771ab5a3005627da4aba57d437ae) you are using quotations for the table name parameter which makes it impossible to work for a table prefixed with the schema name.

See our implementation below:

` new RateLimiterPostgres(
					{
						// Database config
						storeType: 'knex',
						tableCreated: true,
						tableName: 'server.rate_limiters',
						// Limiter config
						keyPrefix: name,
						points,
						duration,
					},`

**Comment by paulsc54** [comment]
Double quotes are used to indicate identifiers within the database (tables, column names, roles, etc.). Therefore schema and database names have to be used as distinct identifiers. To enhance clarity, consider introducing a new parameter, `schemaName`, and employing it in this manner: `${schemaName}.${tableName}`. (btw the parameter could be optional as by default postgres will target the public schema).

Regarding the `dbName` you referenced, its role doesn't extend to becoming a part of the query. Once the connection is established with the driver, the accessed database is implicit. Hence, our focus remains on specifying the schema and table.

**Comment by animir** [comment]
@paulsc54 Ok, thank you.
We should introduce new parameter `schemaName`, so it would be clear for postgres users.
As a temporary fix you can downgrade the package to version `3.0.0`.

Would you be able to make this fix?

**Comment by animir** [comment]
@paulsc54 Thank you!
I merged the PR.

The new version `3.0.2` published.

**Comment by paulsc54** [comment]
Amazing. Thank you!
