### ISSUE TITLE
RateLimiterMemory blockDuration doesnt work with 1 billion seconds

### ISSUE THREAD

**Issue by tomer-yechiel** [animir/node-rate-limiter-flexible#231]
I setup a RateLimiterMemory with blockDuration.
I expect that if a key is blocked, it will be blocked for the blockDuration period.
but it doesnt happened. the key is blocked only 1 time

how to reproduce, the key should be blocked after the first 3 consume
```
const { RateLimiterMemory } = require('rate-limiter-flexible');

const rateLimiterMemory = new RateLimiterMemory({
  keyPrefix: 'key',
  points: 10,
  duration: 5,
  blockDuration: 1000000000,
});

setInterval(async () => {
  try {
    await rateLimiterMemory.consume('t', 3);
    console.log('worked');
  } catch (e) {
    console.log('blocked');
  }
}, 1000);

```

https://stackblitz.com/edit/stackblitz-starters-4no3y9?file=index.js

**Comment by animir** [comment]
@tomer-yechiel Hi, thanks for reporting.
You set `blockDuration` to 1 billion seconds (1000 billion milliseconds) which is over the supported limit.
You can see the warning when running the provided example.

```js
(node:10) TimeoutOverflowWarning: 1000000000000 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
```
Could you tell why you need so long block duration?

**Comment by animir** [comment]
I changed the issue title so it doesn't mislead others.

**Comment by tomer-yechiel** [comment]
got it, I missed the error.
I think it should be added to the documentation.
I will just lower the number, 32bit integer is fine :)

**Comment by animir** [comment]
@tomer-yechiel If you need forever block it should be done other way. You may set `duration` to 0 and a key would be blocked forever after consuming all the `points`.
