### ISSUE TITLE
RateLimiterMemory msBeforeNext is negative in Vercel edge function

### ISSUE THREAD

**Issue by leo-cheron** [animir/node-rate-limiter-flexible#238]
I've been testing this lib on a nextjs edge middleware hosted on Vercel, and I'm facing an issue where `msBeforeNext` would not be reset when its value is < 0, or randomly after waiting for a bit (probably edge function being cold?). The value will continue being decremented under 0 and point won't be reset.

Here's a simplified version of the middleware:

```js
const rateLimiter = new RateLimiterMemory({
	points: 20,
	duration: 5,
})

export const middleware = async (req: NextRequest) => {
	try {
		const res = await rateLimiter.consume(req.ip, 1)
	} catch (error) {
		return NextResponse.rewrite(new URL('/429', req.url), {status: 429})
	}

	return NextResponse.next()
}
```

Catched error would return an object like:

```js
{
  _remainingPoints: 15,
  _msBeforeNext: -2009,
  _consumedPoints: 5,
  _isFirstInDuration: false
}
```

**Comment by marcus13371337** [comment]
I've the same problem!

**Comment by animir** [comment]
@leo-cheron @marcus13371337 Hi, guys. Thank you for reporting!
It is fascinating bug. In some rare cases expired keys are not cleaned up. It is not robust to rely on `setTimeout`, that's how expired keys should be removed.Curious why on Vercel `setTimeout` is not called for 2 seconds like in the example above. This seems pretty long delay. May be they have some under-the-hood optimization.

Anyway. The fix landed in `3.0.5`.

**Comment by leo-cheron** [comment]
> @leo-cheron @marcus13371337 Hi, guys. Thank you for reporting! It is fascinating bug. In some rare cases expired keys are not cleaned up. It is not robust to rely on `setTimeout`, that's how expired keys should be removed.Curious why on Vercel `setTimeout` is not called for 2 seconds like in the example above. This seems pretty long delay. May be they have some under-the-hood optimization.
> 
> Anyway. The fix landed in `3.0.5`.

Seems ok after a couple of tests, closing.

**Comment by marcus13371337** [comment]
Actually, I wasn't in the cloud, but locally on my computer. Was trying with 5 points/second and ran into the issue

**Comment by animir** [comment]
@marcus13371337 What Node.js version do you have on your local?

**Comment by marcus13371337** [comment]
v18.16.0!

**Comment by ayZagen** [comment]
@animir using node@20.12.2, rate-limiter-flexible@5.0.0 with redis I confirm this bug exists. Should I create a new issue for this?

**Comment by animir** [comment]
@ayZagen Hi, if you use RateLimiterRedis then yes, please, create another issue.
