### ISSUE TITLE
Cache data being stored in multiple DB in redis

### ISSUE THREAD

**Issue by abhi2687** [animir/node-rate-limiter-flexible#25]
Observed that rate limiter is caching points consumed/remaining in redis in multiple database. There are 16 DB available in Redis and data is being cached into selected DB when data is being upsert to Redis. I would suggest their should be option to pass in which DB index should be used in Redis to maintain cache

**Comment by abhi2687** [comment]
I can add this fix I already made the changes let me know if you guys want me to push it

**Comment by animir** [comment]
@abhi2687 hey, good idea.

There is `dbName` option which is used for other DBs, it should be used to set db index.

It'd good, if you create a pull request.

**Comment by animir** [comment]
I close this one, be free to open, whenever you wish.
