### ISSUE TITLE
RateLimiterMongo TypeError: Cannot read properties of null (reading 'value')

### ISSUE THREAD

**Issue by o-ali** [animir/node-rate-limiter-flexible#251]
jumping on this question because im seeing a similar issue and was wondering if it had to do with buffering. 

I see error `Cannot read properties of null (reading 'value')`  when the first call is made, and every call after succeeds as long as the entry in the database hasnt been deleted for that key.

Is this a bug with the rate limiter that isnt handling null from the value properly on the first call, it should expect that the first call will not have any entry in the database.

edit: adding context

```
TypeError: Cannot read properties of null (reading 'value')
    at RateLimiterMongo._getRateLimiterRes (node_modules\rate-limiter-flexible\lib\RateLimiterMongo.js:118:23)
    at RateLimiterMongo._afterConsume (node_modules\rate-limiter-flexible\lib\RateLimiterStoreAbstract.js:51:22)
    at node_modules\rate-limiter-flexible\lib\RateLimiterStoreAbstract.js:205:16
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

using rate limiter with the following setup

```
        const opts: IRateLimiterMongoOptions = {
            storeClient: db, // await mongoose.connect(uri).then((res) => res.connection)
            points: 3, 
            duration: 5, 
            tableName: 'rate-limiter',
        };
        rateLimiter = new RateLimiterMongo(opts);
```

```
    "mongoose": "^8.0.1",
    "mongodb": "^6.2.0",
```

_Originally posted by @o-ali in https://github.com/animir/node-rate-limiter-flexible/issues/216#issuecomment-1907606108_

I've traced the issue to the way the rate limiter tries to fetch the version which is erroring here https://github.com/animir/node-rate-limiter-flexible/blob/master/lib/RateLimiterMongo.js#L13 because `topology` is undefined, this results in assuming a version 0 and calls findoneandupdate without returning a result due to it not setting `upsertOptions.returnDocument = 'after';` 

Not sure if mongoose or mongodb recently changed the format of the mongoclient class, but it may be more reliable to instead fetch the client info from `client.client.options.metadata` which gives an object that looks like this

```
{
  driver: { name: 'nodejs|Mongoose', version: '6.2.0|8.0.1' },
  platform: 'Node.js v20.10.0, LE',
...
```

**Comment by animir** [comment]
Fixed in `v4.0.1`. Thank you.
