### ISSUE TITLE
How to prevent negative values

### ISSUE THREAD

**Issue by thetutlage** [animir/node-rate-limiter-flexible#254]
I am using the `reward` method and would like to avoid the counter from going to negative points, because them starts to impact the `consume` method calls.

Here's a quick example.

```ts
const opts = {
  points: 2, // 6 points
  duration: 1, // Per second
};

const rateLimiter = new RateLimiterMemory(opts)
await rateLimiter.reward('ip_address', 1)

// Now I can consume 3 points because I rewarded one additional
// point
await rateLimiter.consume('ip_address', 1)
await rateLimiter.consume('ip_address', 1)
await rateLimiter.consume('ip_address', 1)
```

The behavior of dipping to negative values might be useful for some cases. However, not in my case. So is there any way I can disallow negative values? Or, will be open to adding a new option for the same? I can do a PR for it

**Comment by animir** [comment]
@thetutlage Hi, will getting points before rewarding work for your case? It breaks atomicity, yes, but in some cases it works.
You would get points, check if there is more than 0 and only then reward.
