### ISSUE TITLE
Cannot read property 'collection' of undefined with RateLimiterMongo

### ISSUE THREAD

**Issue by tero** [animir/node-rate-limiter-flexible#26]
I'm implementing rate limit functionality with RateLimiterMongo and `_initCollection` function throws `TypeError: Cannot read property 'collection' of undefined`. Changing `this.client.db` to `this.client` from rows 80 and 81 will fix the issue.

This is with MongoDB version 3.4.10.

**Comment by animir** [comment]
@tero Hi, could you paste rate limiter config here and which nodejs library you use for MongoDB?

**Comment by tero** [comment]
For example this will fail. `models` is our internal package and `models.connection` is `mongoose.connection`.

```javascript
const { RateLimiterMongo } = require('rate-limiter-flexible')
const models = require('models')

const rateLimiter = new RateLimiterMongo({
  storeClient: models.connection,
  tableName: 'rate-limits',
  points: 3, // 3 requests
  duration: 60, // per 60 seconds by IP
})
```

I think the problem is that this is executed immediately when module is loaded by require and connection is not established yet. `mongoose.connection` will pool the requests but `mongoose.connection.db` is not available.

**Comment by animir** [comment]
@tero Is it correct, that you use `models.connection` before you have established connection with mongoose? If so, what is a reason to postpone?

**Comment by animir** [comment]
@tero Which version of mongoose do you use?

**Comment by tero** [comment]
I am using Mongoose 4.13.17.

How we establish and use connection in our project is quite simple and that relies on mongoose's ability to buffer requests:
```javascript
const express = require('express')
const models = require('models')
// Require routes and that means also rate limiter object is initialized.
// Because collection and indexes are created on init it will query database now
const routes = require('./routes')
const app = express()

// Connect to database. Because this is asynchronous action we can't be sure when connection is available but thanks to query buffer we don't have to worry about that.
models.connect({ mongoUrl: process.env.DB_URI })
app.use(routes)

app.listen(3000, () => console.log(`Server listening on port 3000!`))
```

**Comment by animir** [comment]
@tero I see now, thanks. 81 line is for `mongoose` support, so there is just one line should be fixed. Native driver can't buffer commands, as I know.

Would you like to make a PR?

**Comment by tero** [comment]
Glad to see my pull request was accepted. Do you have plans to release new version soon? I would like to wait for new version but if it won't happen in near future then we have to take forked version in use.
