### ISSUE TITLE
Offer Option on consume() Method to Trigger Block on Zero Remaining Points

### ISSUE THREAD

**Issue by valeeum** [animir/node-rate-limiter-flexible#270]
The current implementation of blockDuration in the rate-limiter-flexible package states: "If blockDuration is a positive number and more points are consumed than available."

I would like to request an enhancement to the consume() method to allow for the option to trigger a block if the remaining points reach 0, without exceeding the available points. My use case involves performing a preliminary lookup with the get() method. If remaining points is zero, i return a 4XX error.  If user does have remaining points, I then use the consume() method with 1 point, but if it hits the threshold, it never triggers the block duration.

This feature would be highly beneficial for scenarios where a strict threshold needs to be enforced without the need to over-consume points to trigger a block.

Proposed Enhancement:

Add an option to the consume() method to trigger a block if the remaining points are 0.
Ensure that the block is triggered without exceeding the available points.

**Comment by animir** [comment]
@valeeum Hi, once limiter has 0 remaining points you could call [set](https://github.com/animir/node-rate-limiter-flexible/wiki/API-methods#ratelimitersetkey-points-secduration) method to set points equal to your limiter setting (that's the case when remaining is zero) for `secDuration`.
