### ISSUE TITLE
How to avoid unnecessary consumption of points when using RateLimiterUnion?

### ISSUE THREAD

**Issue by LionelB5** [animir/node-rate-limiter-flexible#280]
I was intending on using `RateLimiterUnion` to rate limit requests my backend is making to a third-party API. The third-party API imposes the following rate limits:
- Max of 10 requests per second
- Max of 100 requests per minute

I am operating in a distributed environment (lambda), with multiple lambda instances reaching out to the same API concurrently, I thought I'd be able to leverage `RateLimiterUnion` along with `RateLimiterDynamo` like so to ensure I remain beneath the rate limits:

```ts
const perSecondLimiter = new RateLimiterDynamo({
  duration: 1,
  points: 10,
  keyPrefix: "per-second",
  storeClient: new DynamoDB(),
  tableName: "rate-limiter-table",
  tableCreated: true,
});
const perMinuteLimiter = new RateLimiterDynamo({
  duration: 60,
  points: 100,
  keyPrefix: "per-minute",
  storeClient: new DynamoDB(),
  tableName: "rate-limiter-table",
  tableCreated: true,
});
const limiter = new RateLimiterUnion(perSecondLimiter, perMinuteLimiter);

limiter
  .consume("foo-api")
  .then((res) => {
    // perform third-party API request
  })
  .catch((rej) => {
    // either perSecondLimiter failed or perMinuteLimiter failed
  });
```

But after looking at the `RateLimiterUnion` implementation, my understanding is that points are consumed needlessly if one of the rate limiters provided to `RateLimiterUnion` throws an error, while the other does not.

For instance, given the limiters defined in the example above, take the following example:
1. 10 points are consumed in 500ms. No rate limiting errors occur.
2. 100ms later, an attempt to consume 90 more points occurs.
    - `perSecondLimiter` detects that consuming these points would exceed the 10 points per second limit and as a result reports that the operation would exceed the specified rate limit.
    - `perMinuteLimiter` does not report an error, since fewer than 100 points have been consumed in the last 60 seconds. This results in `perMinuteLimiter` consuming points, but it doesn't make sense to consume points in this scenario, since `perSecondLimiter` indicated that making a request would exhaust rate limiting quotas (hence the actual requests were not made).
3. The limiter continues to report rate limiting errors for the next 59 seconds and 400ms. But it shouldn't, since in step 2, we couldn't actually consume those 90 points/make a request to our API because `perSecondLimiter` failed.

This seems like a pretty typical use-case for `RateLimiterUnion`, could you please advise if there is any way to get around the issue I'm facing? Many thanks.

**Comment by animir** [comment]
@LionelB5 Hey, thank you for the thoughtful description, appreciate it.

I've never seen such a case where you would need to consume 90 points when one of the limiters allows only 10.
I suggest checking if points could ever be consumed from your RateLimiterUnion.
```
If (pointsToConsume > perSecondLimiter.points) {
   return Promise.reject('Not allowed)
}
```

This will keep your minute limiter from trouble.

**Comment by LionelB5** [comment]
Hey @animir - Thanks very much for your reply, much appreciated. Actually, the example I provided was flawed and confusing and didn't illustrate what I was trying to get across, I'm sorry about that.

Please consider this scenario instead:

1. The same rate limiters as discussed in the original comment at the top of this issue are used.
2. 10 points are consumed in 100ms. No rate limiting errors.
3. Every 100ms, for the next 900ms, 10 points are consumed. Each time we attempt to consume points, the `perSecondLimiter` throws an error indicating the rate limits would be exceeded, beacuse of this no request is actually made.
4. At this point, 1 second has elapsed. A request is made to consume 10 points. In this case the `perSecondLimiter` does not indicate a rate limiting error, but the `perMinuteLimiter` does, because from the perspective of the `perMinuteLimiter`, 100 points have now been consumed.
5. Requests are blocked for the next 59 seconds, but they shouldn't be, given we've only actually made requests amounting to the consumption of a total of 10 points.

Is there something I'm fundamentally misunderstanding? This behaviour seems like a pretty significant limitation of `RateLimiterUnion`. Thank you for your input and advice.

**Comment by animir** [comment]
Thank you for the detailed description. I see now what you meant.

> 5. Requests are blocked for the next 59 seconds, but they shouldn't be, given we've only actually made requests amounting to the consumption of a total of 10 points.

This is not exactly correct. Requests should be blocked anyway. After the `1 second` limiter points are reset, it will allow another request and at that time the `1 minute` limiter will consume points. The `1 minute` limiter will stop requests as it should. The problem you describe still there. I request is counted that, probably, shouldn't be counted. That depends on the of course. I've never met a case where it would be important, but I understand it may be.

I suggest you to use [reward](https://github.com/animir/node-rate-limiter-flexible/wiki/API-methods#ratelimiterrewardkey-points--1) method to refill points on the `1 minute` limiter if `1 second` limiter fails.

**Comment by animir** [comment]
Or you can improve RateLimiterUnion by implementing a new way of consuming points. This mode could be enabled with a new `consumeOneByOne` option.

**Comment by LionelB5** [comment]
> Another option is to create two separate limiters and consume points in sequence. First, from 1 second limiter and then from 1 minute limiter.

Thanks @animir - we will give this a try and see how we go. For what it's worth, I guess this solution is a little imperfect, given it could behave strangely in scenarios where for whatever reason, the network call to the second limiter takes greater time to resolve than the duration specified for the first limiter (perhaps due to extreme load on the database, or network related problems). And with an approach like this, where requests are made sequentially, I feel it would probably be unwise to add more than 2 limiters, excessive network requests and what I suspect to be potential race conditions, if one is using a networked store.

Regardless, I think this will be workable for us for now. Thank you for taking the time to share your thoughts and help out with the question. Much appreciated :+1:

**Comment by animir** [comment]
You're welcome @LionelB5 
One more thought is you could call `get` method from both limiters before consuming from `RateLimiterUnion`. When you have `get` result for both you could decide if you should or shouldn't `consume` from `RateLimiterUnion`. It would save your limiters from unnecessary consume calls and would solve the issue with always blocked minute limiter.

**Comment by animir** [comment]
Closing this one. Feel free to re-open if needed.
