### ISSUE TITLE
not compatible with Next.js 14?

### ISSUE THREAD

**Issue by jcyuan** [animir/node-rate-limiter-flexible#282]
here is the warning log the building reports:

```
./node_modules/rate-limiter-flexible/lib/RateLimiterCluster.js
A Node.js API is used (process.setMaxListeners at line: 290) which is not supported in the Edge Runtime.
Learn more: https://nextjs.org/docs/api-reference/edge-runtime

./node_modules/rate-limiter-flexible/lib/RateLimiterCluster.js
A Node.js API is used (process.on at line: 296) which is not supported in the Edge Runtime.
Learn more: https://nextjs.org/docs/api-reference/edge-runtime

./node_modules/rate-limiter-flexible/lib/RateLimiterCluster.js
A Node.js API is used (process.send at line: 305) which is not supported in the Edge Runtime.
Learn more: https://nextjs.org/docs/api-reference/edge-runtime
```
so on...

so this lib is not compatible with Next.js 14?

or i can use memory store only?

thank you.

**Comment by animir** [comment]
@jcyuan Hey, you can import memory or any other limiter directly like this:
```
import RateLimiterMemory from "rate-limiter-flexible/lib/RateLimiterMemory.js";
```

**Comment by jcyuan** [comment]
> import RateLimiterMemory from "rate-limiter-flexible/lib/RateLimiterMemory.js";

yeah, this is what i did exactly, only import the `memory` one, but i'm not sure why the `cluster` one got included...

this is my code:
```typescript
import 'server-only';

import { RateLimitConfig } from './config';
import { IRateLimiterOptions, RateLimiterMemory } from 'rate-limiter-flexible';

// TODO: use Redis for distributed rate limiting
function createLimiter(config: IRateLimiterOptions) {
    return new RateLimiterMemory(config);
}

export const RateLimiters = Object.fromEntries(
    Object.entries(RateLimitConfig).map(([key, value]) => [key, createLimiter(value)])
);
```

**Comment by jcyuan** [comment]
> > import RateLimiterMemory from "rate-limiter-flexible/lib/RateLimiterMemory.js";
> 
> yeah, this is what i did exactly, only import the `memory` one, but i'm not sure why the `cluster` one got included...
> 
> this is my code:
> 
> ```ts
> import 'server-only';
> 
> import { RateLimitConfig } from './config';
> import { IRateLimiterOptions, RateLimiterMemory } from 'rate-limiter-flexible';
> 
> // TODO: use Redis for distributed rate limiting
> function createLimiter(config: IRateLimiterOptions) {
>     return new RateLimiterMemory(config);
> }
> 
> export const RateLimiters = Object.fromEntries(
>     Object.entries(RateLimitConfig).map(([key, value]) => [key, createLimiter(value)])
> );
> ```
> 
> i think i can't import it like this right? because i found that in the index.js it exports everything. so you mean i have to just directly import from the memory limiter right? let me have a try. thank you!

failed, it seems can't only import RateLimiterMemory in TS dev?

**Comment by jcyuan** [comment]
> > import RateLimiterMemory from "rate-limiter-flexible/lib/RateLimiterMemory.js";
> 
> yeah, this is what i did exactly, only import the `memory` one, but i'm not sure why the `cluster` one got included...
> 
> this is my code:
> 
> ```ts
> import 'server-only';
> 
> import { RateLimitConfig } from './config';
> import { IRateLimiterOptions, RateLimiterMemory } from 'rate-limiter-flexible';
> 
> // TODO: use Redis for distributed rate limiting
> function createLimiter(config: IRateLimiterOptions) {
>     return new RateLimiterMemory(config);
> }
> 
> export const RateLimiters = Object.fromEntries(
>     Object.entries(RateLimitConfig).map(([key, value]) => [key, createLimiter(value)])
> );
> ```
> 
> i think i can't import it like this right? because i found that in the index.js it exports everything. so you mean i have to just directly import from the memory limiter right? let me have a try. thank you!

import { RateLimiterMemory } from 'rate-limiter-flexible/lib/RateLimiterMemory';

works, but it pops error: `Could not find a declaration file for module 'rate-limiter-flexible/lib/RateLimiterMemory'. 'x:/proj/node_modules/rate-limiter-flexible/lib/RateLimiterMemory.js' implicitly has an 'any' type.`

**Comment by jcyuan** [comment]
nvm, temporarily used // @ts-ignore to fix it.

**Comment by animir** [comment]
@jcyuan That's interesting.
You extracted part of type definitions for RateLimiterMemory, right?
Could we somehow add your file to the repo in a way that could be useful for cases like yours?

**Comment by jcyuan** [comment]
> @jcyuan That's interesting. You extracted part of type definitions for RateLimiterMemory, right? Could we somehow add your file to the repo in a way that could be useful for cases like yours?

yes, but my final solution was modifying the `index.js` to exclude the `RateLimiterCluster` from the export list because i found that this is the one caused the problem. (yes it's not recommended to modify a npm lib directly but simple and fast solution though, and i don't need to have another .d.ts)

btw, another solution is, change the runtime as Node.js instead of Edge runtime, problem will be solved too and you can use `Cluster` too which is strongly recommended.

by default Next.js on Vercel uses Node.js runtime, so i believe my case is quite rare, can almost be ignored.

thanks for your reply @animir appreciated it.
