### ISSUE TITLE
RateLimiterRedis: MOVED error from Redis Cluster when using node-redis package

### ISSUE THREAD

**Issue by andrewplu** [animir/node-rate-limiter-flexible#283]
EVAL method is buggy in Node-Redis package:

Redis client sends request to a wrong cluster node, therefore Redis returns a MOVED error.
https://github.com/redis/node-redis/issues/2811

I guess, we should at least add a note somewhere in docs, that RateLimiterRedis doesn't work in Cluster mode with latest node-redis library (v4.7.0)

**Comment by animir** [comment]
@andrewplu Hey, thank you! I put a note about that in docs here https://github.com/animir/node-rate-limiter-flexible/wiki/Redis#redis-package.
