### ISSUE TITLE
Can this package supports X-Forwarded-For ?

### ISSUE THREAD

**Issue by ithinco** [animir/node-rate-limiter-flexible#31]
For example, if I use different IPs via proxy service to attack a public API, can this package shield this kind of attack?

A reference implementation example: [https://eggjs.org/en/tutorials/proxy.html#configmaxproxycount](https://eggjs.org/en/tutorials/proxy.html#configmaxproxycount)

Thanks.

**Comment by animir** [comment]
@ithinco Thanks for the question.

We keep this flexible. You can pass to `consume` or any other method any `key` you want.

For example, you can read how to deal with expressjs behind proxy [here](https://expressjs.com/en/guide/behind-proxies.html)
