### ISSUE TITLE
duration vs blockDuration

### ISSUE THREAD

**Issue by hburrows** [animir/node-rate-limiter-flexible#32]
I'm not understanding the relationship between `duration` and `blockDuration`.  Using the example "Login endpoint protection" in the wiki if I set my `RateLimiterRedis` configuration as:

```
const limiterConsecutiveFailsByUsernameAndIP = new RateLimiterRedis({
  storeClient: redisClient,
  keyPrefix: 'login_fail_consecutive_username_and_ip',
  points: 5,
  duration: 60 * 60 * 24 * 90, // Store number for 90 days since first fail
  blockDuration: 30
});
```

after 5 failed login attempts I'm locked out for 90 days-- the calculated retrySec is ~ 7776000 and any subsequent login attempts are blocked (until I delete my redis keys).  I'm purposely setting the `blockDuration` to 30 (i.e. 30 seconds) for testing.  Once it's working as expected I'll change to 1 hour (60 * 60) or something reasonable.

How do these 2 settings work together?  For testing and understanding how this works I've set `duration` to 60 and `blockDuration` to 30, but only `duration` seems to matter and I reset 60 seconds after the first failed attempt.  Once max `points` have been consumed in `duration` that appears to be it.  How does `blockDuration` matter at all?

**Comment by hburrows** [comment]
I keep re-reading the docs... I feel if I set `points` to 5, `duration` to 30, and `blockDuration` to 60 it would imply if I make 5 unsuccessful login attempts in 30 seconds then I should be blocked for 60 seconds.  But that doesn't work either.  It's like `blockDuration` is meaningless.

I know I'm missing something basic.  I'm happy to make a PR to the docs once I get this understood.

**Comment by animir** [comment]
@hburrows I've just tested it

```javascript
const rateLimiter = new RateLimiterRedis({
  redis: redisClient,
  points: 1,
  duration: 5,
  blockDuration: 10,
});

const srv = http.createServer((req, res) => {
  if (req.url === '/favicon.ico') {
    res.writeHead(404);
    res.end();
    return;
  }
  rateLimiter
    .consume(
      'test', 1
      // Math.floor(Math.random() * 10)
    )
    .then((rlRes) => {
      res.end(JSON.stringify(rlRes));

    })
    .catch((rej) => {
      res.writeHead(429);
      res.end(JSON.stringify(rej));
    });
});

srv.listen(3002);
```

It works like a charm.

Could you post your code here?

**Comment by animir** [comment]
@hburrows 
> How do these 2 settings work together?

Relation of those [described in Wiki](https://github.com/animir/node-rate-limiter-flexible/wiki/Options#blockduration)

`If positive number and consumed more than points in current duration, block for blockDuration seconds.`

**Comment by hburrows** [comment]
@animir Thanks for the quick response.  I think I found the issue.  `rateLimiter.get` is returning the wrong values... or it's correct and intentionally doesn't incorporate `blockDuration` like `rateLimiter.consume`.

Here's an example modified from yours (sorry, but it's in typescript).  Also, for Typescript, I needed to change `IRateLimiterStoreOptions.redis` to `IRateLimiterStoreOptions.storeClient`... don't know which is preferred but I suspect `redis` is legacy.

```
const rateLimiter = new RateLimiterRedis({
  storeClient: redisClient,
  points: 2,
  duration: 5,
  blockDuration: 10
});

const srv = http.createServer(async (req: Request, res: Response) => {
  if (req.url === '/favicon.ico') {
    res.writeHead(404);
    res.end();
    return;
  }
  try {
    const currRlRes = await rateLimiter.get('test');
    if (currRlRes && currRlRes.remainingPoints <= 0) {
      res.writeHead(429);
      res.end(JSON.stringify({ status: 'BLOCKED', ...currRlRes }));
      return;
    }

    const rlRes: RateLimiterRes = await rateLimiter.consume(
      'test', 1
      // Math.floor(Math.random() * 10)
    );

    res.end(JSON.stringify({ status: 'OK', ...rlRes }));
  }
  catch (rej) {
    res.writeHead(429);
    res.end(JSON.stringify({ status: 'BLOCKED', ...rej }));
  }
});

srv.listen(3002);
```

GREAT library by the way.  Thanks for your work and contribution.

**Comment by animir** [comment]
@hburrows yes, you're right, `redis` option is legacy

I've tested `get` method with this code
```javascript
  rateLimiter
    .consume(
      'test', 1
      // Math.floor(Math.random() * 10)
    )
    .then(async () => {
      const getRes = await rateLimiter.get('test');
      res.end(JSON.stringify(getRes));

    })
    .catch(async () => {
      res.writeHead(429);
      const getRes = await rateLimiter.get('test');
      res.end(JSON.stringify(getRes));
    });
```

it works. 
May be you expected, `get` rejects as consume does, when points consumed or blocked?

**Comment by hburrows** [comment]
@animir I changed my example to call `get` AFTER calling `consume` and it works.  So I believe there's a dependency that after consuming the final point you must call `consume` another time for `get` to reflect the correct values -- or you must always call `consume` for values to get updated.

Change your example to call `get` before calling `consume` as per the "Login endpoint protection" example and see what happens.  Here's a vanilla JS example you can copy/paste. 

```
const srv = http.createServer((req, res) => {
  if (req.url === '/favicon.ico') {
    res.writeHead(404);
    res.end();
    return;
  }

  rateLimiter.get('test')
  .then((currRlRes) => {
    if (currRlRes && currRlRes.remainingPoints <= 0) {
      res.writeHead(429);
      res.end(JSON.stringify({ status: 'GET BLOCKED', ...currRlRes }));
      return;
    }

    rateLimiter.consume('test', 1)
    .then((rlRes) => {
      res.end(JSON.stringify({ status: 'CONSUME OK', ...rlRes }));
    })
    .catch((rlRes) => {
      res.writeHead(429);
      res.end(JSON.stringify({ status: 'CONSUME BLOCKED', ...rlRes }));
    });
  });
});
```

`get` will never reflect `blockDuration` and will always be remaining `duration`.   There appears to be a __very important__ dependency:  after the last `point` is consumed another call to `consume` must occur for the `msBeforeNext` values to reflect `blockDuration`.

If this is the desired behavior then the wiki "Login endpoint protection" example needs to be changed.  I personally think this is a bug but it really depends on the intended semantics of `get`.

I structured my code per the "Login endpoint protection" example in the wiki.  The following from the wiki example does not work because it's calling `get` prior to `consume` resulting in incorrect `RateLimiterRes` values.

```
  const [resUsernameAndIP, resSlowByIP] = await Promise.all([
    limiterConsecutiveFailsByUsernameAndIP.get(usernameIPkey),
    limiterSlowBruteByIP.get(ipAddr),
  ]);

  let retrySecs = 0;

  // Check if IP or Username + IP is already blocked
  if (resSlowByIP !== null && resSlowByIP.remainingPoints <= 0) {
    retrySecs = Math.round(resSlowByIP.msBeforeNext / 1000) || 1;
  } else if (resUsernameAndIP !== null && resUsernameAndIP.remainingPoints <= 0) {
    retrySecs = Math.round(resUsernameAndIP.msBeforeNext / 1000) || 1;
  }
```

The values in `resSlowByIP.msBeforeNext` and `resUsernameAndIP.msBeforeNext` will always be remaining `duration` and not reflect `blockDuration` even though `remainingPoints` will be zero and a `blockDuration` was configured.

**Comment by animir** [comment]
@hburrows You're right, good catch. It never reaches `consume`, since `get` returns `remainingPoints === 0` and 429 error.

We can check `consumedPoints` instead of remaining
I've modified the example
```javascript
  if (resSlowByIP !== null && resSlowByIP.consumedPoints > maxWrongAttemptsByIPperDay) {
    retrySecs = Math.round(resSlowByIP.msBeforeNext / 1000) || 1;
  } else if (resUsernameAndIP !== null && resUsernameAndIP.consumedPoints > maxConsecutiveFailsByUsernameAndIP) {
    retrySecs = Math.round(resUsernameAndIP.msBeforeNext / 1000) || 1;
  }
```

In this case it reaches one more consume and blocks it for `blockDuration` seconds.

**Comment by hburrows** [comment]
@animir That works.  Thanks!!  Feel free to close this issue.  Hopefully, I helped lower the barrier for the next user.  Thanks for this great library and your outstanding support maintaining it.

**Comment by animir** [comment]
@hburrows Thank you for your help
