### ISSUE TITLE
Implement RateLimiterFirestore.

### ISSUE THREAD

**Issue by peek4y** [animir/node-rate-limiter-flexible#38]
Any thoughts on implementing the storage class for Firestore / Firebase? 

This would be great for the firebase cloud functions :) since firestore is part of the package.

**Comment by animir** [comment]
@peek4y It would be good. I've never worked with Firestore / Firebase.
Does it support upsert function to make atomic increment? (You may look into Mongo limiter, to see an example, how it is done there)

**Comment by peek4y** [comment]
I suppose yes, https://firebase.googleblog.com/2019/03/increment-server-side-cloud-firestore.html - `FieldValue.increment(value)` does the atomic increment on the server end.

**Comment by animir** [comment]
@peek4y 
```don't forget that documents are still limited to a sustained write limit of 1 QPS per document```
Do you think, it may be not enough?

Do you have an idea how to store expiring time? Does Firestore / Firebase has TTL for documents?

**Comment by peek4y** [comment]
I guess that wouldn't be enough considering there will be more writes per second, hope I'm not wrong. My bad, I missed out that detail.

I don't think there is any TTL for the firestore documents, I guess we would've to run some code to periodically check for expiration (store timestamp and check) or something like that. I'm clueless on this. 

Any idea, on how we could make this work?

**Comment by animir** [comment]
@peek4y There is `RateLimiterMySQL` without built-in TTL, for example. Every row stores additional `expire` value, which is source of true. 

There is an article about Firestore [Distributed Counters](https://firebase.google.com/docs/firestore/solutions/counters). May be this helps. 
[Scheduled functions](https://firebase.google.com/docs/functions/schedule-functions) could help to delete expired documents.
Could you continue investigation and try it?

**Comment by peek4y** [comment]
Sure, I can give it a shot, will probably try it out this weekend.

**Comment by animir** [comment]
@peek4y Hi, have you started implementation?

**Comment by animir** [comment]
Closing this, feel free to re-open.
