### ISSUE TITLE
Feature: key exception (IP exception) - black/white list

### ISSUE THREAD

**Issue by OsoianMarcel** [animir/node-rate-limiter-flexible#4]
Would be great to have an option where we can pass a list of key exceptions (array of strings).
It's useful when you want to not track points for epecific keys (IP Whitelist).

**Comment by animir** [comment]
@OsoianMarcel thanks for the suggestion
The main idea of this package is to keep flexibility, clearness and avoid too much options.

If you need white/black list, you can add some logic and don't consume/check points for certain keys.
For example:
```
async () => {
  try {
    if (!isWhiteListed(key)) {
      await rateLimiter.consume(key)
    }
  } catch (rej) {
    // Disallowed action
  }
  // Allowed action
}
```

**Comment by OsoianMarcel** [comment]
I already have a wrapper for your library where I integrated this feature.
Ok, then you can close this issue.
Thanks.

**Comment by animir** [comment]
@OsoianMarcel that's nice. this gets me another idea.

May be we can add not options, but separate wrapper class `BlackAndWhiteListWrapper`

```
const rl = new BlackAndWhiteListWrapper({
  limiter: anyRateLimiter,
  blackList: [],
  whiteList: [],
  isBlack: () => {},
  isWhite: () => {},
});
```
It should have the same unified API as all other limiters (all methods `get`, `consume`, etc)
This would allow to add wrapper without changing any code.

In the future, if we have several wrappers, we'd add some function `rateLimiterWrap`, which wraps any limiter by configured wrappers.

What do you think?

**Comment by OsoianMarcel** [comment]
Yes, it is a good idea.

**Comment by animir** [comment]
@OsoianMarcel Are you going to make PR?

**Comment by OsoianMarcel** [comment]
Not now, I'm overloaded with work. Sorry.

**Comment by animir** [comment]
no worries, I'll create another issue and close this one
