### ISSUE TITLE
Promise.all inside trycatch

### ISSUE THREAD

**Issue by ejose19** [animir/node-rate-limiter-flexible#41]
This will trigger an Unhandled promise rejection when one of the promises rejects (specifically the next request after remainingPoints is 0)

There's a discussion on stackoverflow and many solutions proposed (see https://stackoverflow.com/a/54291660/3934172)

**Comment by animir** [comment]
@ejose19 Could you provide more context? Where did you find it?

**Comment by ejose19** [comment]
I used the example provided in the wiki (https://github.com/animir/node-rate-limiter-flexible/wiki/Overall-example#login-endpoint-protection) and was getting unhandled promise rejections when limiterSlowBruteByIp was called by Promise.all the first time there's no more remainingPoints.

I checked the source of this library and found that the error was caused by (https://github.com/animir/node-rate-limiter-flexible/blob/2f55f54d410073e0b840a3826241c3c1f586f555/lib/RateLimiterStoreAbstract.js#L69). The try-catch in the example is not able to catch that rejection because that's not how Promise.all works.

The two ways I found to avoid this issue were:

- Instead of using Promise.all, call the commands sequentially:

```
try {
    await limiterSlowBruteByIP.consume(ipAddr);
    if (user.exists) {
        await limiterConsecutiveFailsByUsernameAndIP.consume(usernameIPkey);
    }
} catch {
    error logic there
}
```

With this way the try-catch properly catchs when the promise rejects.

- Drop try-catch and attach .catch for each promise:

```
let error;
let retryMs;
const errorHandler = (rlRejected: any) => {
    error = true;
    eRetryMs = rlRejected.msBeforeNext;
};
const promises = [
    limiterSlowBruteByIP.consume(ipAddr).catch(errorHandler)
];
if (user.exists) {
    promises.push(
        limiterConsecutiveFailsByUsernameAndIP
        .consume(usernameIPKey)
        .catch(errorHandler)
     );
}
await Promise.all(promises);
if (error) {
    error logic there
}
```

**Comment by animir** [comment]
@ejose19 I see.
I made two changes in that example:
1. I put `>=` on comparing consumed points with maximum limit: `resSlowByIP.consumedPoints >= maxWrongAttemptsByIPperDay`. It should never reach `'email or password is wrong'` case now.
2. `consume` method replaced with `penalty` method, which doesn't reject even if there are consumed point over limit.

Regarding handling Promise.all inside try/catch:
I created this test snippet. I don't see any unhandled rejections on launch. Is this correct example?

```
async function run() {
  try {
    await Promise.all([
      Promise.reject(new Error('1')),
      Promise.reject(new Error('2')),
    ])
  } catch (err) {
    console.log(err)
  }
}

run()
```

**Comment by ejose19** [comment]
Try with
```javascript
async function run() {
  try {
    await Promise.all([
      setTimeout(() => Promise.reject(new Error('1')), 1000),
      setTimeout(() => Promise.reject(new Error('2')), 2000),
    ])
  } catch (err) {
    console.log(err)
  }
}
```

To simulate an async operation (in this case redis read/write), and you will get
 the unhandled promise rejections.

**Comment by animir** [comment]
@ejose19 this is not correct code. `setTimeout` returns nothing, so they are really out of the scope.

**Comment by ejose19** [comment]
Yes, you're right. Seems the issue I was  getting was related to using instanceof Error + some specific tweak. Works correctly with newer [`RateLimiterRes`](https://github.com/animir/node-rate-limiter-flexible/pull/42).

One question though, why is .penalty() used instead of .consume() in

```javascript
try {
  const promises = [limiterSlowBruteByIP.penalty(ipAddr)];
  if (user.exists) {
    // Count failed attempts by Username + IP only for registered users
    promises.push(limiterConsecutiveFailsByUsernameAndIP.penalty(usernameIPkey));
  }
  await Promise.all(promises);
  res.status(400).end('email or password is wrong');
    } catch (rlRejected) {
      if (rlRejected instanceof Error) {
        throw rlRejected;
      } else {
        res.set('Retry-After', String(Math.round(rlRejected.msBeforeNext / 1000)) || 1);
        res.status(429).send('Too Many Requests');
      }
  }
```

From what I checked in API docs, penalty won't throw rejected when there's no more points to consume, which I assume is the original goal else that res.X.send is redundant (will never be called). Also if we're using resSlowByIP.consumedPoints >= maxWrongAttemptsByIPperDay (equal or higher instead of just higher) there won't be any time .consume() will reject due "no more points to consume".

Closing as the original issue is not a problem, however I still think that example requires a tweak.

**Comment by ejose19** [comment]
Can't post a pull request to the wiki, so will leave the updated method here:

```javascript
const express = require("express");
const redis = require("redis");
const { RateLimiterRedis, RateLimiterRes } = require("rate-limiter-flexible");
const redisClient = redis.createClient({
  enable_offline_queue: false
});

const maxWrongAttemptsByIPperDay = 100;
const maxConsecutiveFailsByUsernameAndIP = 10;

const limiterSlowBruteByIP = new RateLimiterRedis({
  storeClient: redisClient,
  keyPrefix: "login_fail_ip_per_day",
  points: maxWrongAttemptsByIPperDay,
  duration: 60 * 60 * 24,
  blockDuration: 60 * 60 * 24 // Block for 1 day, if 100 wrong attempts per day
});

const limiterConsecutiveFailsByUsernameAndIP = new RateLimiterRedis({
  storeClient: redisClient,
  keyPrefix: "login_fail_consecutive_username_and_ip",
  points: maxConsecutiveFailsByUsernameAndIP,
  duration: 60 * 60 * 24 * 90, // Store number for 90 days since first fail
  blockDuration: 60 * 60 // Block for 1 hour
});

const getUsernameIPkey = (username, ip) => `${username}_${ip}`;

async function loginRoute(req, res) {
  const ipAddr = req.ip;
  const usernameIPkey = getUsernameIPkey(req.body.email, ipAddr);

  const [resUsernameAndIP, resSlowByIP] = await Promise.all([
    limiterConsecutiveFailsByUsernameAndIP.get(usernameIPkey),
    limiterSlowBruteByIP.get(ipAddr)
  ]);

  let retrySecs = 0;

  // Check if IP or Username + IP is already blocked
  if (
    resSlowByIP !== null &&
    resSlowByIP.consumedPoints > maxWrongAttemptsByIPperDay
  ) {
    retrySecs = Math.round(resSlowByIP.msBeforeNext / 1000) || 1;
  } else if (
    resUsernameAndIP !== null &&
    resUsernameAndIP.consumedPoints > maxConsecutiveFailsByUsernameAndIP
  ) {
    retrySecs = Math.round(resUsernameAndIP.msBeforeNext / 1000) || 1;
  }

  if (retrySecs > 0) {
    res.set("Retry-After", String(retrySecs));
    res.status(429).send("Too Many Requests");
  } else {
    const user = authorise(req.body.email, req.body.password);
    if (!user.isLoggedIn) {
      // Consume 1 point from limiters on wrong attempt and block if limits reached
      try {
        const promises = [limiterSlowBruteByIP.consume(ipAddr)];
        if (user.exists) {
          // Count failed attempts by Username + IP only for registered users
          promises.push(
            limiterConsecutiveFailsByUsernameAndIP.consume(usernameIPkey)
          );
        }

        await Promise.all(promises);

        res.status(400).end("email or password is wrong");
      } catch (rlRejected) {
        if (rlRejected instanceof RateLimiterRes) {
          res.set(
            "Retry-After",
            String(Math.round(rlRejected.msBeforeNext / 1000)) || 1
          );
          res.status(429).send("Too Many Requests");
        } else {
          throw rlRejected;
        }
      }
    }

    if (user.isLoggedIn) {
      if (resUsernameAndIP !== null && resUsernameAndIP.consumedPoints > 0) {
        // Reset on successful authorisation
        await limiterConsecutiveFailsByUsernameAndIP.delete(usernameIPkey);
      }

      res.end("authorized");
    }
  }
}

const app = express();

app.post("/login", async (req, res) => {
  try {
    await loginRoute(req, res);
  } catch (err) {
    res.status(500).end();
  }
});
```

**Comment by animir** [comment]
@ejose19 I reverted example back to original.
I forgot that block works only on consume, you're right. I'm leaving this opened to think of improvements of that example later.
