### ISSUE TITLE
Show different error type when key is blacklisted

### ISSUE THREAD

**Issue by jinshunlee** [animir/node-rate-limiter-flexible#46]
Hi, in https://github.com/animir/node-rate-limiter-flexible/wiki/Black-and-White-lists
> If Key is black, consume rejected anytime.

If the key is blacklisted, is there a way to differentiate it in the `RateLimiterRes` object?

From what I see, if the key is blacklisted, the `msBeforeNext` value will be 9007199254740991 forever.

**Comment by animir** [comment]
@jinshunlee Hey. You're right, you could compare `msBeforeNext` with `Number.MAX_SAFE_INTEGER`, if `duration` option on limiter is less than `Number.MAX_SAFE_INTEGER`.

On the other hand, you know blacklisted keys from options set to `RLWrapperBlackAndWhite` instance.
