### ISSUE TITLE
Configurable IP Address

### ISSUE THREAD

**Issue by yquansah** [animir/node-rate-limiter-flexible#48]
Hello,

So it seems in the library code that we key only off `req.ip`. There are some cases where that value can be spoofed if you are running Express behind a proxy via the `X-Forwarded-For` header if `trust-proxy` is set to true for the app. I was wondering if it is possible for a consumer of this library to pass an `ip` value in, and fall back to `req.ip` if nothing is passed in.

LOC: https://github.com/animir/node-rate-limiter-flexible/blob/master/lib/ExpressBruteFlexible.js#L148

**Comment by animir** [comment]
@yquansah Hey.
You can enable `ignoreIP` option and put it within key.

However, if you don't trust proxy, it is better to disable `trust-proxy` option.
