### ISSUE TITLE
Automatically revert back to RateLimiterRedis after redis connection recovers

### ISSUE THREAD

**Issue by jinshunlee** [animir/node-rate-limiter-flexible#49]
Is there a way to automatically revert back to `RateLimiterRedis` after redis connection recovers from going down?
 
The code below will continue to use `RateLimiterMemory` even after the redis connection recovers.

```javascript
const redis = require('redis');
const { RateLimiterRedis, RedisLimiterMemory } = require('rate-limiter-flexible');

const redisClient = redis.createClient({
  enable_offline_queue: false,
  retry_strategy: function (options) {
    if (options.attempt > 3) { // Try to reconnect 3 times
      // This error is caught by limiter and then insurance limiter is used in this case
      return new Error('Retry time exhausted');
    }

    return 100; // Not longer than 100 * 3 = 300 ms
  }
});

const rateLimiterMemory = new RateLimiterMemory({
  points: 1,
  duration: 1
});

const rateLimiter = new RateLimiterRedis({
  redis: redisClient,
  points: 5,
  duration: 1,
  insuranceLimiter: rateLimiterMemory
});
```

**Comment by animir** [comment]
@jinshunlee It should automatically use Redis, when it is up. 
Maybe play with `retry_strategy` conditions and make it longer than 300ms?

**Comment by jinshunlee** [comment]
>Maybe play with retry_strategy conditions and make it longer than 300ms?
Ah I see thanks!

```javascript
// This error is caught by limiter and then insurance limiter is used in this case
return new Error('Retry time exhausted');
```

I realised that switching to the `insuranceLimiter` does not rely on this error to trigger, is this comment accurate?

**Comment by animir** [comment]
`redis` package doesn't reject commands immediately depending on `retry_strategy`. When `retry_strategy` attempts exhausted, all promises are rejected and caught by `RateLimiterRedis`. This is the time to use `insuranceLimiter`. I hope, it helps.

**Comment by animir** [comment]
I'm closing this, feel free to re-open
