### ISSUE TITLE
Add ability to define points by key dynamically

### ISSUE THREAD

**Issue by jobeland** [animir/node-rate-limiter-flexible#50]
It would be great to be able to allow further customization of points allowed instead of a sweeping value across all keys. Ex: Allow IP 1 to have 60 points over 60 seconds, but allow IP 2 to only have 30 points over 60 seconds, and allow IP 3 to have a dynamic value (like 2x IP1, or some other call back to have it externally determined), with some sort of default points if not specified. It would also be beneficial to store that in something other than memcache (redis, for example) which would allow users of the library to update/specify the points for a key after it has been deployed so it can be updated dynamically as the situations arise just by updating the distributed cache.

I imagine this would slow down each request since it would probably be 2 calls to redis, but as an opt-in capability I would be happy to accept that.

**Comment by animir** [comment]
@jobeland This can be achieved by consuming different amount of points depending on conditions.

**Comment by jobeland** [comment]
@animir to make sure I understand correctly, is your suggest to flip the calculation around and instead of dynamically specifying points per IP, to instead specify points _consumed_ per IP? Based off your basic example. Something like:
```
const opts = {
  points: 1000, // Some really large amount to divide from
  duration: 60, // Per second
};
 
const rateLimiter = new RateLimiterMemory(opts);
 
rateLimiter.consume(remoteAddress, redisClient.get(remoteAddress)) // consume a dynamic amount of points
    .then((rateLimiterRes) => {
      // X points consumed
    })
    .catch((rateLimiterRes) => {
      // Not enough points to consume
    });
```

**Comment by animir** [comment]
@jobeland yeah, that's right

**Comment by jobeland** [comment]
This should be more than sufficient, thanks for the tip!
