### ISSUE TITLE
Replace use of whitelist and blacklist

### ISSUE THREAD

**Issue by moog** [animir/node-rate-limiter-flexible#51]
Terminologies such as `whitelist` and `blacklist` have historical context, making their meaning unclear. A substitution for `allowlist` and `denylist` would bring more direct meaning. The same goes for `isWhite` and `isBlack`, which can be replaced by `isAllowed` and `isDenied`.

I am aware that this would represent a breaking change, but I still consider it valid. Meanwhile it is possible to correct these terminologies internally on the library.

**Comment by macabeus** [comment]
I'm agree with that, but I think that we should keep the compatibility with old names.
So, replace doc and code to allow to use `isAllowed` and `isDenied`, but add `isWhite` and `isBlack` as nickname to `isAllowed` and `isDenied`.

**Comment by animir** [comment]
@moog `whitelist` and `blacklist` terms are used a lot in different areas like: politics, networking, employment, etc. Many people already know what it is.

In addition, these terms are helpful in context of this package, as it already allows and denies depending on other conditions, but `blacklist` and `whitelist` terms make it more clear. Certain key may be allowed, denied, blacked or whited. 
I hope, this makes it more clear.

**Comment by animir** [comment]
version `1.2.1` deprecates `isWhite` and `isBlack` method names. `isWhiteListed` and `isBlackListed` should be used instead.
