### ISSUE TITLE
Can I use one Redis for multiple rate-limiters?

### ISSUE THREAD

**Issue by FMGordillo** [animir/node-rate-limiter-flexible#53]
I have one instance of Redis, and multiple API's from different endpoints. Can I use the same Redis instance for differente backends?

This is just a starting point, don't pretend that it's a production thing

**Comment by animir** [comment]
@FMGordillo Yes, you can. There is [keyPrefix](https://github.com/animir/node-rate-limiter-flexible/wiki/Options#keyprefix) option. Here is [an example](https://github.com/animir/node-rate-limiter-flexible/wiki/Overall-example#different-limits-for-different-parts-of-application)

**Comment by FMGordillo** [comment]
Thank you!
