### ISSUE TITLE
RateLimiterCluster with PM2 cluster mode and Redis as store client

### ISSUE THREAD

**Issue by varunj166** [animir/node-rate-limiter-flexible#56]
Hi there. First, thank you for the excellent library!

I'm having an issue when attemping to implement the RateLimiterCluster with PM2 in cluster mode.

I followed the example you wrote here: 
https://github.com/animir/node-rate-limiter-flexible/wiki/PM2-cluster

However your example doesn't include a 'storeClient' prop passed to the `RateLimiterCluster ` constructor (even though the TS definitions have `IRateLimiterStoreOptions` as the options interface accepted by `RateLimiterCluster`). So I add the `storeClient` prop anyway, which points to my `redisClient` (node-redis), and fire everything up.

It seems as if my redis store isn't being touched at all, even though the rate limiting is working. This suggests to me that even though I specified my `redisClient` as the `storeClient`, `RateLimiterCluster` is actually operating in-memory.

Can you tell me how to hook `RateLimiterCluster` to my redis store? Or perhaps it actually should be in-memory only? And if that's the case, can you change the interface required by the `RateLimiterCluster` constructor to exclude the `storeClient` prop?

Thanks very much!

**Comment by varunj166** [comment]
Quick follow-up question:

If I don't use `RateLimiterCluster` and just continue to use `RateLimiterRedis`, but still deploy my app with PM2 in cluster-mode, the cluster instances are all able to interact with my redis store without any problems. 

So is the problem that when a point is consumed or a block is triggered, the `duration` and `blockDuration` properties will be tracked individually be each process, and so will not be the same across all processes? Or is it completely fine to use `RateLimiterRedis` behind a PM2 cluster deployment?

Thanks!

**Comment by animir** [comment]
@varunj166 Hi, thanks!
If you use `RateLimiterCluster` with PM2, you don't need Redis. It works in memory of master process.
There is a bug in a type description of `RateLimiterCluster` constructor type. It doesn't require `storeClient`, so it shouldn't `IRateLimiterStoreOptions` really. It should be specific type almost the same, but without `storeClient` and with `timeoutMs?: number` option.

> Or is it completely fine to use RateLimiterRedis behind a PM2 cluster deployment?

It is fine to use `RateLimiterRedis` with PM2, since Redis stores counters in this case. The main purpose of `RateLimiterCluster` is minimisation of infrastructure cost, if there is just one server launched in cluster. And `RateLimiterCluster` is faster :)

**Comment by varunj166** [comment]
@animir Thanks for the reply!

So I definitely want to continue to use redis to store points (I'm using redis for other things already for the purposes of scalability), and I'd like to use PM2 in cluster mode for it's load balancing and auto-restart goodies, AND I really like your rate limiting library, but before I can combine all three, I just need to make sure of how a couple things work. I've combed through your source code, but I want to confirm my understanding.

Take this simple scenario:
- App deployed with PM2 in cluster mode with 2 instances -- I'll call them iA and iB.
- `RateLimiterRedis` at the top of the middleware stack (in each instance) tracking all incoming requests by ip address. `RateLimiterRedis` has a `points` of 5 per `duration` of 10 minutes, and a `blockDuration` of 24 hours.

Flow:
1) A request comes from 0.0.0.0, and pm2 directs it to **iA**.
- `RateLimiterRedis` in iA sends a `set` command to redis to set `rlKey` to 1, with 'EX' of `duration` and 'NX' flag enabled.
2) Another request comes from 0.0.0.0, and pm2 this time directs it to **iB**.
- `RateLimiterRedis` sends the same command as (1), but redis ignores it because the key exists, and returns null. Because the return was null, `RateLimiterRedis` fires an `incrby` command, which returns the current `consumedPoints`. The value of the key is now 1.
3) More requests come in from 0.0.0.0, with pm2 directing to iA or iB depending on traffic, and `RateLimiterRedis` increments the points up until we hit 5.
4) Another request comes from 0.0.0.0, and pm2 has directed the request to **iA**.
- This time when `RateLimiterRedis` increments `consumedPoints`, and retrieves the `RateLimiterRes`, it identifies that the `consumedPoints` is greater than the initial `opts.points`, and executes a `block`method.
- The block method sets a new expiry on the key inside redis, setting it to `opts.blockDuration`.

**What comes next is what I am not sure of:**

5) Another request comes in from 0.0.0.0, and pm2 directs it to **iA**.
- `RateLimiterRedis` again increments the points count, identifies that `pointsConsumed` > `opts.points`, but... somehow knows that this key is already blocked, and so doesn't execute another block command, and the expiry on the key is still what it was set to in (3)?
6) A final request comes in from 0.0.0.0, and pm2 directs it to **iB** this time.
- All the same as (4), and somehow the `RateLimiterRedis` here in iB **also** knows that that key is already blocked, and so the expiry on the key in redis remains the same as it was et to in (3)?

So if I'm right about (1), (2), and (4), can you confirm that iB knows that the key has been blocked, even though the block was triggered from iA, and so won't try to 're-block' the key, thereby changing the expiry of the key in redis?

**Bottom-line, even though points are being consumed by both iA and iB separately, it is not necessary for them to be aware of who triggered the block on a key in order for the block and blockDuration functionality to work properly??**

Thanks so much in advance!

**Comment by varunj166** [comment]
@animir Hey, so I tested your library with a single server, but simulated requests coming into different instances of a cluster by starting and stopping my server while sending new requests after being blocked, and the TTL on the key remained the same.

Looks like your logic that prevents additional blocks on a key after an initial block isn't dependent on some in-memory data, which is fantastic!

This is really an amazing library. It must have taken you a good amount of time to develop, so thank you very very much!

**Comment by animir** [comment]
@varunj166 Good analysis! 
This line https://github.com/animir/node-rate-limiter-flexible/blob/4fea26495ae68b4d883867383c21c8f322258d0b/lib/RateLimiterStoreAbstract.js#L56 makes the trick with blockDuration.
