### ISSUE TITLE
RateLimiterCluster typings do not allow specifying an insuranceLimiter

### ISSUE THREAD

**Issue by Page-** [animir/node-rate-limiter-flexible#59]
Looking at the code it appears that RateLimiterCluster accepts an insuranceLimiter and this is purely a limitation of the typings, however I wanted to check that was the case before PRing a change

**Comment by animir** [comment]
@Page- Hi, Cluster limiter uses memory limiter in master process , and memory limiter doesn't require insurance. 

Could you point, where RateLimiterCluster accepts insurance limiter?

**Comment by Page-** [comment]
Ah I've spotted my confusion, I missed the distinction between `RateLimiterStoreAbstract` and `RateLimiterAbstract` and though the `RateLimiterClusterWorker` extended from `RateLimiterStoreAbstract`. My follow on question then is should `RateLimiterClusterWorker` support an insurance strategy as it can timeout communicating with `RateLimiterClusterWorker` according to https://github.com/animir/node-rate-limiter-flexible/blob/5893ac735d25f1a35cdd34aa0f6f620e7b22e6ab/lib/RateLimiterCluster.js#L186-L189 ?

**Comment by animir** [comment]
@Page- `RateLimiterCluster` is really something in between `RateLimiterAbstract` and `RateLimiterStoreAbstract`. I think, it is not necessary to provide insurance for cluster. If cluster limiter can't handle amount of traffic and times out, it is unlikely insurance limiter helps. Thoughts?

**Comment by Page-** [comment]
The main case it would handle is when the cluster master is unresponsive for some other reason, eg if running something that blocks the event loop on the master. I'd say that generally the master worker should be pretty isolated though so in practice that shouldn't be an issue so I think it's fine to leave
