### ISSUE TITLE
Burst requests using leaky bucket size

### ISSUE THREAD

**Issue by matomesc** [animir/node-rate-limiter-flexible#61]
Is there any way to implement a leaky bucket algorithm with bucket size in order to allow burst requests?

For example a bucket of size 10 with 2 req/s leak rate allows up to 10 burst requests which fill the bucket and then only 2 req/s while the bucket remains full. If there are no requests, then the bucket empties at the 2 req/s leak rate, allowing another 10 burst requests after 5 seconds.

This is the implementation of the `bottleneck` library: https://github.com/SGrondin/bottleneck#increase-interval

**Comment by animir** [comment]
@matomesc Hi. 
This package doesn't provide that logic exactly, but there is an option.
You can create [BurstyRateLimiter](https://github.com/animir/node-rate-limiter-flexible/wiki/BurstyRateLimiter) and use it with [RateLimiterQueue](https://github.com/animir/node-rate-limiter-flexible/wiki/RateLimiterQueue).

```javascript
const burstyLimiter = new BurstyRateLimiter(
  new RateLimiterMemory({
    points: 2,
    duration: 1,
  }),
  new RateLimiterMemory({
    keyPrefix: 'burst',
    points: 8,
    duration: 5,
  })
);

const limiter = new RateLimiterQueue(limiterFlexible, {
  maxQueueSize: 10,
});
```

This rate limited FIFO queue allows to queue up not more than 10 requests. It executes 2 requests per second and allows traffic burst up to 10 every 5 seconds.

**Comment by matomesc** [comment]
Thanks appreciate your help!
