### ISSUE TITLE
Wrapping a RateLimiterRedis with many RateLimiterQueues

### ISSUE THREAD

**Issue by behrad** [animir/node-rate-limiter-flexible#62]
We have a situation where we want to rate limit actions on individual record IDs. Rate limiter queue on top of a Redis limiter handles this job for us, but we need it to consume per record ID however current RateLimiterQueue [calls consume with a hardcoded limiter name](https://github.com/animir/node-rate-limiter-flexible/blob/ccb5f5c10455e6af5d0a84d9db5615523251db9d/lib/RateLimiterQueue.js#L36)

Any chance to make `_key` parametric in queue constructor or a `removeTokens` overload with `_key` parameter so that we can dynamically use many granular queues over a single limiter instance?

**Comment by animir** [comment]
@behrad Hey. 
It should be set as additional option `key` in the second `opts` attribute  of `RateLimiterQueue` constructor. You could create as many RateLimiterQueue instances as you need with different keys.

**Comment by behrad** [comment]
Yup @animir and I think [this is not currently possible](https://github.com/animir/node-rate-limiter-flexible/blob/ccb5f5c10455e6af5d0a84d9db5615523251db9d/lib/RateLimiterQueue.js#L9)
If I am right, could you elaborate on when is your roadmap for this to be available?

**Comment by animir** [comment]
@behrad This is not possible now, you are right. 
I don't have time for this at least until the weekend in two weeks. Feel free to implement it earlier. 

Note, it requires to write a test to make sure queue limiter works with custom key.

**Comment by animir** [comment]
@behrad Hi. You can use new key param with functions `removeTokens(tokens, key)` and `getTokensRemaining(key)` now.

Hope this helps.

**Comment by behrad** [comment]
👍 @animir Feels great, Thank you for your promising efforts on this nice handy project. I enjoy using your little sexy designed module ❤️ 
Let me check this & let you know!

**Comment by animir** [comment]
@behrad Hi, how is it going? Any feedback?

**Comment by behrad** [comment]
> @behrad Hi, how is it going? Any feedback?

Sorry for my late response, I tested against latest version yesterday and it now serves me as expected. Great job @animir 👍
