### ISSUE TITLE
Fibonacci blocking example is not clear

### ISSUE THREAD

**Issue by idangozlan** [animir/node-rate-limiter-flexible#63]
Hi,

Thanks for the great module.
I'm having hard time with the Fibonacci example for login blocking, I guess that it will be really helpful to get also the `limiterConsecutiveOutOfLimits` and `loginLimiter` definitions.  

Thanks!

**Comment by animir** [comment]
@idangozlan Hey.

I've updated related [example](https://github.com/animir/node-rate-limiter-flexible/wiki/Overall-example#dynamic-block-duration)
Hope, this helps.

**Comment by idangozlan** [comment]
Thanks for the awesome example! It was a super-fast response ;)
