### ISSUE TITLE
Where is authorise() defined?

### ISSUE THREAD

**Issue by OctaneInteractive** [animir/node-rate-limiter-flexible#64]
Hi!

I've added [an example](https://github.com/animir/node-rate-limiter-flexible/wiki/Overall-example#login-endpoint-protection) to an existing application but it doesn't work.

I've traced the failure down to the `authorise(req.body.email, req.body.password)`, where it comes to a halt, defaulting to the 500 error.

Nothing after the call to the method runs, including `console.log()`, there are no additional errors, and it's failing with valid sign in credentials.

I don't see where the method is defined in the IDE I'm using, and there's no further discussion regarding it.

**Comment by animir** [comment]
@OctaneInteractive Hey,

It is specific for your project. You should implement it to authorise users.

**Comment by OctaneInteractive** [comment]
Hi @animir, I did think that was the case but I needed to check.
