### ISSUE TITLE
How to make it working with AWS Lambda

### ISSUE THREAD

**Issue by bhushankumarl** [animir/node-rate-limiter-flexible#65]

**Comment by animir** [comment]
@bhushankumarl Hi. I've never tried. Could you describe more, what do you want to achieve?

**Comment by animir** [comment]
@bhushankumarl How is it going? Were you able to use this package with AWS Lambda?

**Comment by bhushankumarl** [comment]
@animir 
I am using this package into the AWS Lambda but as Lambda functions work as the serverless it doesn't able to keep the state of the lat point.

**Comment by animir** [comment]
@bhushankumarl You could use limiter with connection to a store like Redis, MongoDB, etc. 

You can also implement a new limiter for DynamoDB. It supports atomic increments, you can read more [here](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/WorkingWithItems.html#WorkingWithItems.AtomicCounters). It is quite simple.
[Contribution quide is here](https://github.com/animir/node-rate-limiter-flexible#contribution).

**Comment by bhushankumarl** [comment]
@animir 
Thank you for following on this. I will take a look.

Closing this issue as of now.
