### ISSUE TITLE
Queue all consume calls until point can be resolved

### ISSUE THREAD

**Issue by matomesc** [animir/node-rate-limiter-flexible#66]
Essentially I'm looking for a way to call `consume` so that it resolves when the points can be consumed - in other words no `RateLimiterRes` is thrown and consumes are automatically queued. 

Right now I'm doing something like this (concurrency can be added to match with limiter):

```js
while (true) {
  await limiter.consume(key);
} catch (err) {
  if (err instanceof RateLimiterRes) {
    await sleep(err.msBeforeNext);
  } else {
    throw err;
  }
}
```

I looked at using the `RateLimiterQueue` but it has concurrency of 1 due to FIFO order. However I could wrap the same limiter with several `RateLimiterQueue` such that the number of queues equals the number of points that can be consumed in the duration.

But I feel like since the limiter already knows how the points can be consumed, it can also queue all the consume calls.

**Comment by animir** [comment]
@matomesc Hi. 
`RateLimiterQueue` doesn't limit concurrency. It uses `err.msBeforeNext` to set timeout like in your example. All free points are consumed as soon as possible, if there are waiting requests in FIFO queue.

I hope, this helps.

**Comment by matomesc** [comment]
Thanks, I was under the impression that it consumes one at a time. Are there any plans to make the queue compatible with the burst rate limiter?

**Comment by animir** [comment]
@matomesc That's a good question. It is almost compatible now. If you are not using TypeScript and `getTokensRemaining` method from `RateLimiterQueue`, you can safely use it now. 

Otherwise, you should fix `RateLimiterQueue` constructor argument type to allow `BurstyRateLimiter` class. And also you should implement `get` method in `BurstyRateLimiter` in class.

**Comment by animir** [comment]
@matomesc Hey, fell free to close this ticket, if you're not going to make above enhancements.

**Comment by animir** [comment]
@matomesc 
> Are there any plans to make the queue compatible with the burst rate limiter?

version `2.1.9` supports this
