### ISSUE TITLE
Redis DB

### ISSUE THREAD

**Issue by Zarinia** [animir/node-rate-limiter-flexible#67]
Hi,
How can i use redis with select db number for insert data

**Comment by animir** [comment]
@Zarinia Hi, Redis client connection options or string should have `db` attribute. Which package do you use?

**Comment by Zarinia** [comment]
I develope with nodejs and redis-connection,
and use redis with 15 dbs number
I used redis dbs for many purpose ,
such as db1 for logs
db2 for tmp and etc...
I would like to use limit brute force to store data in db4
inside of project i used redis  like this to select db number and insert:
db.select(1, function(err,res){
  db.set('key', 'string'); // this will be posted to database 1 rather than db 0
});
But  when i used this after that somebody request to my server , limit brute check insert data in db 1 not db4
because in previous select my redis set to 1 and i want that your package insert data in db 4 in all around project
thanks

**Comment by animir** [comment]
@Zarinia Are you able to select Redis DB before any limiter function execution like you do in other cases? For example, if you `consume` points, you should select DB and then `consume` inside callback.

**Comment by Zarinia** [comment]
Wow thanks
it's work very fine,
If you let me, i have another question
can i change response time with count of request?
for example:
 i create brute force with 5 req per 10 sec
if any one send 6th request my response time take longer to answer
if any one send 7th request my response time take too longer?

**Comment by animir** [comment]
@Zarinia thanks.
check [this example](https://github.com/animir/node-rate-limiter-flexible/wiki/Overall-example#dynamic-block-duration)

**Comment by Zarinia** [comment]
@animir tank you,
I think set time out or insert sleep may be a good idea for response with point limiter

**Comment by animir** [comment]
@Zarinia you're welcome. feel free to close this ticket whenever you want

**Comment by Zarinia** [comment]
Thanks a lot and best regards to you
