### ISSUE TITLE
add node-rate-limiter to benchmark

### ISSUE THREAD

**Issue by musicformellons** [animir/node-rate-limiter-flexible#7]
Could you maybe include https://github.com/jhurliman/node-rate-limiter in your benchmark?

**Comment by animir** [comment]
@musicformellons thanks for the idea, I will include it probably, but `node-rate-limiter` works in memory only, which is not quite useful for 90-95% (?) of applications. 

however, I'll search through github and include some the most famous.

**Comment by animir** [comment]
I've added comparison to https://github.com/ded/express-limiter
thanks
closing this issue
