### ISSUE TITLE
RateLimiterQueue

### ISSUE THREAD

**Issue by Zarinia** [animir/node-rate-limiter-flexible#70]
Hi, How can i use RateLimiterQueue for every user ip,
and set ip as key on redis like limiterSlowBruteByIP
I want to limited every user by RateLimiterQueue with different token

**Comment by animir** [comment]
@Zarinia Hi, there is no convenient way yet. Similar ticket is waiting PR https://github.com/animir/node-rate-limiter-flexible/issues/62

You can create limiter with `keyPrefix` option as IP every time user makes request though. It is not exactly what you asked, but should work fine.

**Comment by animir** [comment]
@Zarinia Hi. You can use new key param with functions removeTokens(tokens, key) and getTokensRemaining(key) now.

I hope this helps.

**Comment by Zarinia** [comment]
Hi, sorry for my late reply,
It worked very well, thank you very much
I wish you the best

**Comment by animir** [comment]
@Zarinia Nice. I'm closing this ticket

All the best to you as well.
