### ISSUE TITLE
error: TimeoutOverflowWarning

### ISSUE THREAD

**Issue by sido420** [animir/node-rate-limiter-flexible#71]
Sorry, for the lack of details initially. I think I accidentally pressed submit/Enter.

Here is the stack trace
```
3|app  | error: TimeoutOverflowWarning: 2592000000 does not fit into a 32-bit signed integer.
3|app  | Timeout duration was set to 1.
3|app  |     at new Timeout (internal/timers.js:59:15)
3|app  |     at setTimeout (timers.js:414:19)
3|app  |     at MemoryStorage.set (/srv/node_modules/rate-limiter-flexible/lib/component/MemoryStorage/MemoryStorage.js:36:36)
3|app  |     at MemoryStorage.incrby (/srv/node_modules/rate-limiter-flexible/lib/component/MemoryStorage/MemoryStorage.js:25:17)
3|app  |     at Promise (/srv/node_modules/rate-limiter-flexible/lib/RateLimiterMemory.js:22:37)
3|app  |     at new Promise (<anonymous>)
3|app  |     at RateLimiterMemory.consume (/srv/node_modules/rate-limiter-flexible/lib/RateLimiterMemory.js:19:12)
```

**Comment by sido420** [comment]
This happens sometimes, but I dont know how to reproduce it yet.

**Comment by animir** [comment]
@sido420 Hi, What is `duration` option value?

**Comment by sido420** [comment]
I did a `JSON.stringify()` on the limiter just before the exception:
```
{"_points":50000000,"_duration":2592000,"_blockDuration":43200,"_execEvenly":false,"_execEvenlyMinDelayMs":52,"_keyPrefix":"Lgn-pfx","_memoryStorage":{"_storage":{}}},"max_points":6,"duration":2592000,"blockDuration":43200}
```
Original settings for this limiter:
```
{
            max_points: 6,
            duration: this.dayInSeconds * 30,
            blockDuration: this.dayInSeconds / 2,
            getKey: (req): string => this.getUsernameIPkey(req) 
        }
```

`readonly dayInSeconds: number = (60 * 60 * 24);`

**Comment by animir** [comment]
@sido420 Memory limiter uses `setTimeout` under the hood. It is not supposed to store points for os long. There is a note about it here: https://github.com/animir/node-rate-limiter-flexible/wiki/Memory

> maximum duration for memory limiter is 2147483 seconds or about 24 days because of setTimeout limitation.

**Comment by sido420** [comment]
The good thing is its been documented here with the error message, so others will benefit as well.

Thanks for clarification.
