### ISSUE TITLE
Production throw unhandledRejection warning

### ISSUE THREAD

**Issue by suhaotian** [animir/node-rate-limiter-flexible#72]
In production(run after build with webpack) throw `unhandledRejection`

The error output:
```ts
{ 
  remainingPoints: 0,
  msBeforeNext: 900000,
  consumedPoints: 5,
  isFirstInDuration: false 
}
```

**Comment by suhaotian** [comment]
In development mode didn't have this warning

**Comment by animir** [comment]
@suhaotian Hi, most likely, there is uncaught Promise rejection. what is limiter related code in your project?

**Comment by suhaotian** [comment]
@animir 

This is the express middleware:

```ts
const rateLimiterMiddleware = async (
    req: Request,
    res: Response,
    next: NextFunction,
  ): Promise<void> => {
    try {
      const rlResUsername = await rateLimiter.get(getKey(req));
      if (
        rlResUsername !== null &&
        rlResUsername.consumedPoints > maxConsecutiveFailsByUsername
      ) {
        const retrySecs = Math.round(rlResUsername.msBeforeNext / 1000) || 1;
        res.set('Retry-After', String(retrySecs));
        next(new ErrorHandler(429, 'Too Many Wrong Requests'));
      } else {
        next();
      }
    } catch (e) {
      next(e);
    }
  };
```

Hey, Thank you for the fast response

**Comment by animir** [comment]
@suhaotian Where is code block consumes points?

**Comment by suhaotian** [comment]
```ts
route.post(
    '/signin',
    rateLimiterMiddleware,
    async (req: Request, res: Response, next: NextFunction) => {
      try {
        const { username, password }: SignInReq = req.body;
        const result = await signIn({
          username,
          password,
        });
        rateLimiter.delete(getKey(req));

        return res.status(200).json(result);
      } catch (e) {
        rateLimiter.consume(getKey(req));
        return next(e);
      }
    },
  );
```

**Comment by animir** [comment]
@suhaotian `consume` rejects, when there is not enough points to consume, see this [section in docs](https://github.com/animir/node-rate-limiter-flexible/wiki/API-methods#ratelimiterconsumekey-points--1-options--). You can use [penalty](https://github.com/animir/node-rate-limiter-flexible/wiki/API-methods#ratelimiterpenaltykey-points--1) method instead. However, it can be also rejected on Redis error. You can use `penalty` method with [insuranceLimiter](https://github.com/animir/node-rate-limiter-flexible/wiki/Insurance-Strategy) or add try/catch block. 
Hope, this helps.

**Comment by suhaotian** [comment]
I add try/catch no more reject warning. 
Thank you
