### ISSUE TITLE
Does RateLimiterRedis support ioredis library Cluster mode?

### ISSUE THREAD

**Issue by jpadhye** [animir/node-rate-limiter-flexible#73]
I'm wondering if RateLimiterRedis supports ioredis library in Cluster mode? https://github.com/luin/ioredis#Cluster

I was not able to find any documentation mentioning this.

**Comment by animir** [comment]
@jpadhye Hi. Good question. I have never tested it myself. However, from what ioredis docs say, it should work. `RateLimiterRedis` uses `multi` for transactions, which supported by Cluster mode. And it doesn't chain custom commands. 

Let community know, if you use Cluster mode. Or share any issues.
Thanks.

**Comment by animir** [comment]
@jpadhye Hey, how is it going? have you tried `RateLimiterRedis` in Cluster mode?

**Comment by animir** [comment]
Closing this, any feedback appreciated anyway.
