### ISSUE TITLE
Express, Koa and Hapi wiki update

### ISSUE THREAD

**Issue by angelod1as** [animir/node-rate-limiter-flexible#74]
In Express, Koa and Hapi wiki, the `new RateLimiterRedis` has a wrong property: `redis`.

```javascript
const rateLimiter = new RateLimiterRedis({
  redis: redisClient,
  keyPrefix: 'middleware',
  points: 10, // 10 requests
  duration: 1, // per 1 second by IP
});
```

It's supposed to be `storeClient`.

```javascript
const rateLimiter = new RateLimiterRedis({
  storeClient: redisClient,
  keyPrefix: 'middleware',
  points: 10, // 10 requests
  duration: 1, // per 1 second by IP
});
```

Tested locally and it works like a charm

I can't seem to find a way to make a pull request of these needed updates.
(I'm kinda new to GitHub so if there's a better way to report this, I'd love to know)

**Comment by animir** [comment]
@angelod1as Hi! Thank you for reporting this. I fixed mentioned wiki pages myself. (Unfortunately, github doesn't allow to suggest changed straight to wiki)
