### ISSUE TITLE
500 has been sent before 429?

### ISSUE THREAD

**Issue by skasidej** [animir/node-rate-limiter-flexible#77]
Is it normal for handling too many requests flow to send 500 status and the next call would be 429?

**Comment by animir** [comment]
@skasidej Hi, I don't think so

**Comment by skasidej** [comment]
@animir These are the result that I've got after reaching the limit.

`
POST /login 500
{"remainingPoints":0,"msBeforeNext":60000,"consumedPoints":11,"isFirstInDuration":false}
`

And after post to the same route again, 429 will return instead of 500.

`POST /login 429`

**Comment by skasidej** [comment]
@animir I believe the problem came from mishandling consumed point is exceeding the limit. Case closed! 😎

**Comment by animir** [comment]
@skasidej good catch!
