### ISSUE TITLE
Does the limiter support day duration?

### ISSUE THREAD

**Issue by mt4c** [animir/node-rate-limiter-flexible#80]
I want to set the duration to be one day. And it should start every period at 0:00. Is that possible?

**Comment by animir** [comment]
@mt4c it supports day duration. Just set `duration` in seconds.
This package has dynamic period start: whenever action happens and there is no such `key` in a store yet -> it creates a new key/value with `duration` expiration time in seconds.

However, there is a trick. You can add current date as a suffix to a consumed key, e.g. `limiter.consume(`${userId}_${currentDayOfMonth}`)`. Note, this key would be expired in a day after the first action, so it can lead to some extra data stored for the previous day. But no longer than a day. 

If it is an issue for you, [consume](https://github.com/animir/node-rate-limiter-flexible/wiki/API-methods#ratelimiterconsumekey-points--1-options--) method also supports `customDuration` option, so you can calculate when key should be expired.

Let me know, if it helps.

**Comment by mt4c** [comment]
Thank you very much
