### ISSUE TITLE
Error: Redis connection to redis:6379 failed - getaddinfo ENOTFOUND redit

### ISSUE THREAD

**Issue by Sireini** [animir/node-rate-limiter-flexible#81]
I did copy the Express middle ware js file from here: https://github.com/animir/node-rate-limiter-flexible/wiki/Express-Middleware

But when trying to run it throws me this error: Error: Redis connection to redis:6379 failed - getaddinfo ENOTFOUND redit

**Comment by animir** [comment]
@Sireini I guess, you should install `redis` package. Could you share your `package.json` ?

**Comment by animir** [comment]
@Sireini Can you connect to Redis without `rate-limiter-flexible`?

**Comment by Sireini** [comment]
@animir any command of redis is not found

**Comment by Sireini** [comment]
@animir This worked for me: sudo apt-get install redis-server
