### ISSUE TITLE
negative value for RateLimiterQueue#removeTokens()

### ISSUE THREAD

**Issue by FranckFreiburger** [animir/node-rate-limiter-flexible#82]
According to https://github.com/animir/node-rate-limiter-flexible/issues/47 negative point is ok (same as reward).
Is it also true for RateLimiterQueue (eg. `myRateLimiterQueue.removeTokens(-1)`) ?

**Comment by animir** [comment]
@FranckFreiburger It definitely works with RateLimiterMemory. It is better to test it with other limiters.

**Comment by animir** [comment]
Closing this, feel free to re-open, if you have any questions
