### ISSUE TITLE
remainingPoints and consumePoints stay the same each time I do an request

### ISSUE THREAD

**Issue by Sireini** [animir/node-rate-limiter-flexible#83]
I use the middleware code which you provided:

`const Redis = require("redis");
const { RateLimiterRedis } = require("rate-limiter-flexible");

const redisClient = Redis.createClient();

const rateLimiter = new RateLimiterRedis({
  storeClient: redisClient,
  keyPrefix: "middleware",
  points: 10, // 10 requests
  duration: 1, // per 1 second by IP
});

const rateLimiterMiddleware = (req, res, next) => {
  rateLimiter
    .consume(req.ip)
    .then((result) => {
      console.log("res", result);
      next();
    })
    .catch(() => {
      console.log("err", res);
      res.error("To many requests");
      res.status(429).send("Too Many Requests");
    });
};

module.exports = rateLimiterMiddleware;
`

Each time I do a login it logs me the same values over and over again:

`{
    remainingPoints: 9,
    msBeforeNext: 1000,
    consumedPoints: 1,
    isFirstInDuration: true
}`

In this way the middleware on the login api is never going to show me the res.status(429).send('Too Many Requests')

**Comment by animir** [comment]
@Sireini How long is duration?

**Comment by Sireini** [comment]
@animir I am just spamming so milliseconds. And in config of rateLimiter its: duration: 1, // per 1 second by IP

**Comment by animir** [comment]
@Sireini How do you do login? What is value of `req.ip` in logs?

**Comment by Sireini** [comment]
@animir ::ffff:127.0.0.1

**Comment by animir** [comment]
@Sireini That means, you still have not connected to Redis and all requests made in offline queue.

**Comment by animir** [comment]
@Sireini How is it going? Were you able to fix this issue?

**Comment by animir** [comment]
@Sireini I'm closing this for now. Feel free to re-open it.
