### ISSUE TITLE
Clearing the Redis cache?

### ISSUE THREAD

**Issue by imwillhang** [animir/node-rate-limiter-flexible#86]
Thanks for the amazing library!

Is there ever a situation where `node-rate-limiter-flexible` doesn't clear Redis, and we end up running out of memory in the cache?

**Comment by animir** [comment]
@imwillhang Hi, thanks.

It can be if your app creates a lot of not-expiring keys with duration `0`. Otherwise, keys are cleared by Redis automatically.

**Comment by animir** [comment]
Closing this, feel free to re-open if something pops up
