### ISSUE TITLE
Wiki improvement Suggestion: Example Koa middleware

### ISSUE THREAD

**Issue by NoahCarnahan** [animir/node-rate-limiter-flexible#88]
Thanks for your work on this project!

The example Koa middleware in the [wiki](https://github.com/animir/node-rate-limiter-flexible/wiki/Koa-Middleware) will return a 429 response if any subsequent middleware (such as the route's main handler) throws an exception, not just if `rateLimiter.consume()` throws an exception. I believe replacing with the following code would be an improvement:
```js
app.use(async (ctx, next) => {
  try {
    await rateLimiter.consume(ctx.ip)
  } catch (rejRes) {
    ctx.status = 429
    ctx.body = 'Too Many Requests'
    return  // Subsequent middleware should only be invoked if rate limit check succeeded
  }
  await next()
})
```

and for reference, the current function in the wiki is as follows:
```js
app.use(async (ctx, next) => {
  try {
    await rateLimiter.consume(ctx.ip)
    next()
  } catch (rejRes) {
    ctx.status = 429
    ctx.body = 'Too Many Requests'
  }
})
```

**Comment by animir** [comment]
@NoahCarnahan Hi, this is a good suggestion.

Should it use `throw` method like this?
```javascript
app.use(async (ctx, next) => {
  try {
    await rateLimiter.consume(ctx.ip)
  } catch (rejRes) {
    ctx.throw(429, 'Too Many Requests')
  }
  await next()
})
```

**Comment by NoahCarnahan** [comment]
Hm, that’s a good question. I think you could do it either way, it sort of depends on what your other middleware are expecting. One advantage of not using `ctx.throw()` is that middleware which do something after calling their `next()` function still get a chance to execute.

For instance, consider this basic timing middleware:
```
app.use(async (ctx, next) => {
	let start = Date.now();
	await next();
	let end = Date.now()
	console.log('Request took ' + (end-start) +  ' milliseconds');
});
```
If this timing middleware was above/before the rate limiting middleware, then using `ctx.throw()` would prevent the timing middleware from logging the time it took process the request.

**Comment by animir** [comment]
@NoahCarnahan That's a good point. I combined both this way.

```javascript
app.use(async (ctx, next) => {
  try {
    await rateLimiter.consume(ctx.ip)
  } catch (rejRes) {
    ctx.status = 429
    ctx.body = 'Too Many Requests'
    return // Subsequent middleware should only be invoked if rate limit check succeeded
    // Or you can throw an exception
    // ctx.throw(429, 'Too Many Requests')
  }
  await next()
})
```

Thank you!
