### ISSUE TITLE
Broken links in docs

### ISSUE THREAD

**Issue by mriedem** [animir/node-rate-limiter-flexible#89]
I started using this library yesterday to add some rate limiting with the postgresql backend in our express app and it works great, thank you for writing it and making it so well documented! 🥇 

While perusing the docs I did notice some broken links though so I figured I'd contribute to the project by reporting those (and hopefully finding the time to push a PR which fixes them).

Here are the ones I spotted (at least):

- https://github.com/animir/node-rate-limiter-flexible/wiki/Overall-example#apply-in-memory-block-strategy-for-better-protection
    - From `Setup Insurance Strategy` https://github.com/animir/node-rate-limiter-flexible#middlewares-and-plugins and `Insurance Strategy` https://github.com/animir/node-rate-limiter-flexible/wiki/Overall-example#how-to-protect
- https://github.com/animir/node-rate-limiter-flexible/wiki/Overall-example#create-simple-rate-limiter-and-consume-points-on-entry-point
    - From https://github.com/animir/node-rate-limiter-flexible/wiki/Overall-example#how-to-protect for `Create rate limiter`

**Comment by animir** [comment]
@mriedem Hi, good catch! Fixed listed above

**Comment by mriedem** [comment]
Thanks @animir. I think there was a misunderstanding on the first one though, because the links in the wiki are still wrong (I'm not sure how to edit the wiki, or if that's even possible).

The `Insurance Strategy` link at [1] should link to [2].

[1] https://github.com/animir/node-rate-limiter-flexible/wiki/Overall-example#how-to-protect
[2] https://github.com/animir/node-rate-limiter-flexible/wiki/Overall-example#setup-insurance-strategy-for-store-limiters

**Comment by animir** [comment]
@mriedem I fixed it, thank you.
