### ISSUE TITLE
mongoose problem

### ISSUE THREAD

**Issue by jd1378** [animir/node-rate-limiter-flexible#92]
hi
I just wanted to let you know there's an issue with mongoose going on which you may want to consider: https://github.com/Automattic/mongoose/issues/8810

here is [a comment](https://github.com/Automattic/mongoose/issues/9496#issuecomment-715448949) saying that in v6.0 you can no longer use .then on connections. it will be a breaking change for me, probably for other people as well. just wanted to inform you of this early.

the fix is to rewrite the code so the connection is always available before passing it to rate limiter , but the refactor can be quite large depending on the application.

**Comment by animir** [comment]
@jd1378 Thank you for this note. I think, `RateLimiterMongo` support both Promise returning connection and already established connection. So what you should do is just replacing how you open connection in the new version.
