### ISSUE TITLE
TypeORM Support for RateLimitPostgres

### ISSUE THREAD

**Issue by williamleiby** [animir/node-rate-limiter-flexible#96]
Hello @animir,

I noticed that in the docs for `rate-limiter-flexible`, you allowed for support with Sequelize & Knux for connections to Postgres (I haven't checked to see if the other DB drivers support this integration as well) - I was wondering if there would be support for TypeORM in the future due to its prominence amongst JavaScript/TypeScript-based ORMs? 

Thanks!

**Comment by animir** [comment]
Hi @williamleiby,
Knex and Sequelize support was added for Postgres and MySQL, but it was done quite interesting way. Limiter uses underlaying raw connections to build and make queries to DB. Would it satisfy your needs? I have never used TypeORM myself, but there should be a way to do the same. And it would be quite easy to make it by example.

Of course, there is always long way: implement new rate limiter class specifically for TypeORM, I am afraid it may consume a lot of time. But if you need it, I can help to understand how to implement it.

Hope this helps.

**Comment by animir** [comment]
@williamleiby TypeORM support for RateLimiterPostgres added in version `2.2.1`, thanks to @seromenho
