### ISSUE TITLE
I though expired `key`s  "reappeared" or reset after a number of seconds 

### ISSUE THREAD

**Issue by ahsath** [animir/node-rate-limiter-flexible#99]
I don't understand the logic behind this library, if a key has expired it gets deleted from the db depending on the limiter you choose mine is MongoDB, then if you try to consume points from that deleted key it gets stored in the db with expire set to null, why? aren't the points and duration from the instantiated limiter be picked up after a key gets deleted when calling consume again on the same key? 

According to the wiki you only need at least one limiter instantiated so you can reuse it across the whole server or whatever but supposing you're using it from a REST API point of view at one point you will run out of points and you will need to reward that key to really reset the key in a catch block, also there is no examples in what cases you should use the reward method.

My use case is just for rate limiting a REST API through an api_key as the unique address, and my guess is that either I instantiate several limiters as requests come in if no remaining points or I do some heuristic for rewarding api_keys since these are tied to users plan which can vary in expiration time (hours, month, years)

**Comment by animir** [comment]
@ahsath hi, could you share your limiter options and limiter usage code?

**Comment by ahsath** [comment]
Hi, sure

I'm using Hapi.js and basically I use it as a plugin:

```JS
const { RateLimiterMongo } = require("rate-limiter-flexible");

module.exports = {
  name: "rateLimitMongoDB",
  async register(server) {
    server.decorate(
      "server",
      "limiter",
      new RateLimiterMongo({
        storeClient: server.mongo.client,
        keyPrefix: "",
        dbName: process.env.MONGODB_DB,
        tableName: "apiKeyQuotas",
        duration: 0,
        points: 0,
      })
    );
  },
};
```
Register it:

```JS
  // A little bit of context
  await server.register({
    plugin: require("hapi-mongodb"),
    options: {
      settings: {
        useUnifiedTopology: true,
      },
      url: process.env.MONGODB_URI,
      decorate: true,
    },
  });

  await server.register({
    plugin: require("./plugins/rateLimitMongoDB"),
  });
```
And consume it in a very long handler

```JS
module.exports = {
  method: "GET",
  path: "/fares",
  async handler(req, h) {
    db = req.server.mongo.client.db(process.env.MONGODB_DB);
    limiter = req.server.limiter;
    faresCollection = db.collection("fares");
    apiKeysCollection = db.collection("apiKeys");
    apiKey = req.query.api_key;

    try {
      // To do: add projection to only return the apiKey instead of the whole document
      let apiKeyDoc = await apiKeysCollection.findOne({ apiKey });

      // Throw if api_key is non-existent
      if (!apiKeyDoc) throw Boom.badRequest("api_key non-existent");

      // Consume 1 point for the current api_key
      let { remainingPoints, msBeforeNext } = await limiter.consume(apiKey);

      return (
        h
          // Returns an array of fares or an empty array if no documents are matched
          .response({ data: await faresCollection.find({}).toArray() })
          .code(200)

          // The number of remaining requests in the current time frame
          .header("X-RateLimit-Remaining", remainingPoints)

          // A UNIX timestamp of the expected time when the rate limit will reset
          .header(
            "X-RateLimit-Reset",
            addMilliseconds(new Date(), msBeforeNext).getTime()
          )
      );
    } catch (error) {
      // If Boom re-throw
      if (error.isBoom) throw error;

      if (error instanceof RateLimiterRes) {
        e429 = Boom.tooManyRequests("api_key quota exceeded");

        e429.output.headers["Retry-After"] = Math.round(
          // Convert milliseconds to seconds
          error.msBeforeNext / 1000
        );
        throw e429;
      }
    }
  },
```

**Comment by animir** [comment]
@ahsath Your limiter doesn't have points to consume. You should set maximum points using [points](https://github.com/animir/node-rate-limiter-flexible/wiki/Options#points) option and set [duration](https://github.com/animir/node-rate-limiter-flexible/wiki/Options#duration). Think of it as of points can be consumed per period of time, e.g. 4 points per 10 seconds, that would be a quota for every api key.

**Comment by ahsath** [comment]
The reason behind points and duration being 0 is that I will use the reward method for that purpose.

For example, I will reward 500 points for free accounts for a day or 24 hours per se, I was expecting the limiter to reset itself every 24 hours, I don't see any problems starting with 0 points 0 duration

**Comment by animir** [comment]
@ahsath I see now. Why do you expect to reset points every 24 hours, if you set `duration=0` ? Zero duration means keys never expire.

**Comment by animir** [comment]
@ahsath [consume](https://github.com/animir/node-rate-limiter-flexible/wiki/API-methods#ratelimiterconsumekey-points--1-options--) and [set](https://github.com/animir/node-rate-limiter-flexible/wiki/API-methods#ratelimitersetkey-points-secduration) methods have ability to set a key duration different from limiter's duration. I hope this helps.

**Comment by ahsath** [comment]
> @ahsath I see now. Why do you expect to reset points every 24 hours, if you set `duration=0` ? Zero duration means keys never expire.

I understand this, I'm not relaying on this value because as I said I will be rewarding users with a certain amount of points based on specific criteria (user plan) as far as I know and already tested if I don't call `consume` before calling `reward` no key should be stored forever, so, only after I reward users I call consume with something like this:

```JS
await limiter.reward(apiKey, 5, {
    customDuration: 60 * 5,
})
```
My point and question is, why the key gets deleted from the store after `customDuration`? isn't supposed to stay there and reset after 5 minutes in this example with the points set to -5 each time?

**Comment by animir** [comment]
@ahsath `customDuration` doesn't overwrite limiter's duration option forever. It affects behaviour for this exact operation. Limiter's duration is used once key expired. That's why you see expire set to `null`.

Limiter stores amount of consumed points for every key, it doesn't store number of points available for consume. `points` limiter option set maximum points per key. When maximum points or more consumed, limiter rejects further `consume` calls. Read [this example separation user to authorized and unauthorized groups](https://github.com/animir/node-rate-limiter-flexible/wiki/Overall-example#authorized-and-not-authorized-users). 

If you have certain amount of pricing plans, you can create the same amount of limiter with different options and use them depending on user's plan line in [this example](https://github.com/animir/node-rate-limiter-flexible/wiki/Overall-example#different-limits-for-different-parts-of-application)

**Comment by animir** [comment]
@ahsath btw, you can try to consume with the same `customDuration` option. It should work

```javascript
// This second
let { remainingPoints, msBeforeNext } = await limiter.consume(apiKey, 1, {
    customDuration: 60 * 5,
});
```

**Comment by ahsath** [comment]
I was thinking about it and now reading what you said, I might have confuse the purpose of this library, this is sort of a more general purpose rate limiter not suitable for my use case of counting and storing request calls, I'm going to use it for limiting the amount of request per apikey yes, but realized I will need another way of storing the count.

Thank you for your patience and answers.
